// This file is automatically generated by Citron version 2.0.
//
// The parser class defined below conforms to the CitronParser protocol
// defined in CitronParser.swift. 
// 
// The authors of Citron disclaim copyright to the source code in this file.

// Parser class

class ParenthesizedQueryParser: CitronParser {

    // Types

    typealias CitronSymbolNumber = UInt8
    typealias CitronStateNumber = UInt8
    typealias CitronRuleNumber = UInt8

    enum CitronTokenCode: CitronSymbolNumber {
      case Whitespace                     =   1
      case Or                             =   2
      case OpenParen                      =   3
      case CloseParen                     =   4
      case Verbatim                       =   5
    }

    enum CitronNonTerminalCode: CitronSymbolNumber {
      case query                          =   6
      case disjunction                    =   7
      case conjunction                    =   8
      case term                           =   9
      case literal                        =  10
    }

    enum CitronSymbolCode : RawRepresentable, Equatable {
        case token(CitronTokenCode)
        case nonterminal(CitronNonTerminalCode)
        case endOfInput

        init(_ token: CitronTokenCode) { self = .token(token) }
        init(_ nonterminal: CitronNonTerminalCode) { self = .nonterminal(nonterminal) }
        init(rawValue: CitronSymbolNumber) {
            if (rawValue == 0) {
                self = .endOfInput
            } else if (rawValue < 6) {
                self = .token(CitronTokenCode(rawValue: rawValue)!)
            } else if (rawValue < 11) {
                self = .nonterminal(CitronNonTerminalCode(rawValue: rawValue)!)
            } else {
                fatalError()
            }
        }

        typealias RawValue = CitronSymbolNumber
        var rawValue: CitronSymbolNumber {
            switch (self) {
            case .token(let t): return t.rawValue
            case .nonterminal(let nt): return nt.rawValue
            case .endOfInput: return 0
            }
        }
    }

    typealias CitronToken = ParenthesizedQueryTokenContent

    enum CitronSymbol {
        case yyBaseOfStack
        case yy0(CitronToken)
        case yy11(ParenthesizedQuery)

        func typeErasedContent() -> Any {
            switch (self) {
            case .yyBaseOfStack: fatalError()
            case .yy0(let value): return value as Any
            case .yy11(let value): return value as Any
            }
        }
    }

    typealias CitronResult = ParenthesizedQuery

    // Counts

    let yyNumberOfSymbols: Int = 11
    let yyNumberOfStates: Int = 15

    // Action tables

    let yyLookaheadAction: [(CitronSymbolNumber, CitronParsingAction)] = [
/*   0 */  ( 6, .ACCEPT),   ( 7, .SH( 9)), ( 8, .SH(11)), ( 9, .RD( 3)), (10, .RD( 5)),
/*   5 */  ( 7, .SH( 8)), ( 8, .SH(11)), ( 9, .RD( 3)), (10, .RD( 5)), ( 7, .SH( 6)),
/*  10 */  ( 8, .SH(11)), ( 9, .RD( 3)), (10, .RD( 5)), ( 1, .SH( 2)), ( 3, .SH( 1)),
/*  15 */  ( 3, .SH( 1)), ( 5, .SH(10)), ( 5, .SH(10)), ( 8, .SH(12)), ( 9, .RD( 3)),
/*  20 */  (10, .RD( 5)), ( 1, .SH( 5)), ( 9, .RD( 4)), (10, .RD( 5)), ( 4, .SR( 7)),
/*  25 */  ( 2, .SH(13)), ( 2, .SH(13)), ( 4, .SR( 9)), ( 4, .SR( 8)), ( 1, .SH( 7)),
/*  30 */  ( 0, .RD( 0)), ( 1, .SH(14)), ( 4, .SR( 6)), ( 1, .SH( 4)), ( 5, .SR(11)),
/*  35 */  ( 1, .SH( 3)), (11, .RD( 2)), ( 2, .SH(13)),
    ]

    let yyShiftUseDefault: Int = 38
    let yyShiftOffsetMin: Int = 0
    let yyShiftOffsetMax: Int = 35
    let yyShiftOffset: [Int] = [
        /*     0 */    11,   12,   11,   11,   11,   23,   20,   24,   28,   30,
        /*    10 */    29,   32,   32,   34,   35,
    ]

    let yyReduceUseDefault: Int = -7
    let yyReduceOffsetMin: Int =   -6
    let yyReduceOffsetMax: Int =   13
    let yyReduceOffset: [Int] = [
        /*     0 */    -6,   -2,    2,   10,   13,
    ]

    let yyDefaultAction: [CitronParsingAction] = [
  /*     0 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*     5 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*    10 */  .RD(10), .RD( 1), .RD( 2), .ERROR , .ERROR ,
    ]

    // Fallback

    let yyHasFallback: Bool = false
    let yyFallback: [CitronSymbolNumber] = []

    // Wildcard

    let yyWildcard: CitronSymbolNumber? = nil

    // Rules

    let yyRuleInfo: [(lhs: CitronSymbolNumber, nrhs: UInt)] = [
        (lhs: 6, nrhs: 1),
        (lhs: 7, nrhs: 1),
        (lhs: 7, nrhs: 5),
        (lhs: 8, nrhs: 1),
        (lhs: 8, nrhs: 3),
        (lhs: 9, nrhs: 1),
        (lhs: 9, nrhs: 3),
        (lhs: 9, nrhs: 4),
        (lhs: 9, nrhs: 4),
        (lhs: 9, nrhs: 5),
        (lhs: 10, nrhs: 1),
        (lhs: 10, nrhs: 2),
    ]

    // Stack

    var yyStack: [(stateOrRule: CitronStateOrRule , symbolCode: CitronSymbolNumber, symbol: CitronSymbol)]  = [
        (stateOrRule: .state(0), symbolCode: 0, symbol: .yyBaseOfStack)
    ]
    var maxStackSize: Int? = nil
    var maxAttainedStackSize: Int = 0

    // Tracing

    var isTracingEnabled: Bool = false
    var isTracingPrintsSymbolValues: Bool = false
    var isTracingPrintsTokenValues: Bool = false
    let yySymbolName: [String] = [
    /*  0 */ "$",
    /*  1 */ "Whitespace",
    /*  2 */ "Or",
    /*  3 */ "OpenParen",
    /*  4 */ "CloseParen",
    /*  5 */ "Verbatim",
    /*  6 */ "query",
    /*  7 */ "disjunction",
    /*  8 */ "conjunction",
    /*  9 */ "term",
    /* 10 */ "literal",
    ]
    let yyRuleText: [String] = [
        /*   0 */ "query ::= disjunction(d)",
        /*   1 */ "disjunction ::= conjunction(c)",
        /*   2 */ "disjunction ::= disjunction(d) Whitespace Or Whitespace conjunction(c)",
        /*   3 */ "conjunction ::= term(t)",
        /*   4 */ "conjunction ::= conjunction(c) Whitespace term(t)",
        /*   5 */ "term ::= literal(l)",
        /*   6 */ "term ::= OpenParen(l) disjunction(q) CloseParen(r)",
        /*   7 */ "term ::= OpenParen(l) Whitespace disjunction(q) CloseParen(r)",
        /*   8 */ "term ::= OpenParen(l) disjunction(q) Whitespace CloseParen(r)",
        /*   9 */ "term ::= OpenParen(l) Whitespace disjunction(q) Whitespace CloseParen(r)",
        /*  10 */ "literal ::= Verbatim(v)",
        /*  11 */ "literal ::= Verbatim(v1) Verbatim(v2)",
    ]

    // Function definitions

    func yyTokenToSymbol(_ token: CitronToken) -> CitronSymbol {
        return .yy0(token)
    }

    func yyInvokeCodeBlockForRule(ruleNumber: CitronRuleNumber) throws -> CitronSymbol {
        switch (ruleNumber) {
        case 0: /* query ::= disjunction(d) */
            func codeBlockForRule00(d: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 6)
 d 
#sourceLocation()
}
            if case .yy11(let d) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy11(try codeBlockForRule00(d: d))
            }
        case 1: /* disjunction ::= conjunction(c) */
            func codeBlockForRule01(c: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 9)
 c 
#sourceLocation()
}
            if case .yy11(let c) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy11(try codeBlockForRule01(c: c))
            }
        case 2: /* disjunction ::= disjunction(d) Whitespace Or Whitespace conjunction(c) */
            func codeBlockForRule02(d: ParenthesizedQuery, c: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 10)

    .init(filters: d.filters + c.filters, range: d.range.lowerBound..<c.range.upperBound)

#sourceLocation()
}
            if case .yy11(let d) = yySymbolOnStack(distanceFromTop: 4),
               case .yy11(let c) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy11(try codeBlockForRule02(d: d, c: c))
            }
        case 3: /* conjunction ::= term(t) */
            func codeBlockForRule03(t: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 15)
 t 
#sourceLocation()
}
            if case .yy11(let t) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy11(try codeBlockForRule03(t: t))
            }
        case 4: /* conjunction ::= conjunction(c) Whitespace term(t) */
            func codeBlockForRule04(c: ParenthesizedQuery, t: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 16)

    .init(filters: c.filters + t.filters, range: c.range.lowerBound..<t.range.upperBound)

#sourceLocation()
}
            if case .yy11(let c) = yySymbolOnStack(distanceFromTop: 2),
               case .yy11(let t) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy11(try codeBlockForRule04(c: c, t: t))
            }
        case 5: /* term ::= literal(l) */
            func codeBlockForRule05(l: ParenthesizedQueryTokenContent) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 21)

    .init(filters: [l.range], range: l.range)

#sourceLocation()
}
            if case .yy0(let l) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy11(try codeBlockForRule05(l: l))
            }
        case 6: /* term ::= OpenParen(l) disjunction(q) CloseParen(r) */
            func codeBlockForRule06(l: ParenthesizedQueryTokenContent, q: ParenthesizedQuery, r: ParenthesizedQueryTokenContent) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 24)

    .init(filters: q.filters, range: l.range.lowerBound..<r.range.upperBound)

#sourceLocation()
}
            if case .yy0(let l) = yySymbolOnStack(distanceFromTop: 2),
               case .yy11(let q) = yySymbolOnStack(distanceFromTop: 1),
               case .yy0(let r) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy11(try codeBlockForRule06(l: l, q: q, r: r))
            }
        case 7: /* term ::= OpenParen(l) Whitespace disjunction(q) CloseParen(r) */
            func codeBlockForRule07(l: ParenthesizedQueryTokenContent, q: ParenthesizedQuery, r: ParenthesizedQueryTokenContent) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 27)

    .init(filters: q.filters, range: l.range.lowerBound..<r.range.upperBound)

#sourceLocation()
}
            if case .yy0(let l) = yySymbolOnStack(distanceFromTop: 3),
               case .yy11(let q) = yySymbolOnStack(distanceFromTop: 1),
               case .yy0(let r) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy11(try codeBlockForRule07(l: l, q: q, r: r))
            }
        case 8: /* term ::= OpenParen(l) disjunction(q) Whitespace CloseParen(r) */
            func codeBlockForRule08(l: ParenthesizedQueryTokenContent, q: ParenthesizedQuery, r: ParenthesizedQueryTokenContent) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 30)

    .init(filters: q.filters, range: l.range.lowerBound..<r.range.upperBound)

#sourceLocation()
}
            if case .yy0(let l) = yySymbolOnStack(distanceFromTop: 3),
               case .yy11(let q) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let r) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy11(try codeBlockForRule08(l: l, q: q, r: r))
            }
        case 9: /* term ::= OpenParen(l) Whitespace disjunction(q) Whitespace CloseParen(r) */
            func codeBlockForRule09(l: ParenthesizedQueryTokenContent, q: ParenthesizedQuery, r: ParenthesizedQueryTokenContent) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 33)

    .init(filters: q.filters, range: l.range.lowerBound..<r.range.upperBound)

#sourceLocation()
}
            if case .yy0(let l) = yySymbolOnStack(distanceFromTop: 4),
               case .yy11(let q) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let r) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy11(try codeBlockForRule09(l: l, q: q, r: r))
            }
        case 10: /* literal ::= Verbatim(v) */
            func codeBlockForRule10(v: ParenthesizedQueryTokenContent) throws -> ParenthesizedQueryTokenContent {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 38)
 v 
#sourceLocation()
}
            if case .yy0(let v) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy0(try codeBlockForRule10(v: v))
            }
        case 11: /* literal ::= Verbatim(v1) Verbatim(v2) */
            func codeBlockForRule11(v1: ParenthesizedQueryTokenContent, v2: ParenthesizedQueryTokenContent) throws -> ParenthesizedQueryTokenContent {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 39)

    .init(content: "\(v1)\(v2)", range: v1.range.lowerBound..<v1.range.upperBound)

#sourceLocation()
}
            if case .yy0(let v1) = yySymbolOnStack(distanceFromTop: 1),
               case .yy0(let v2) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy0(try codeBlockForRule11(v1: v1, v2: v2))
            }
        default:
            fatalError("Can't invoke code block for rule number \(ruleNumber) - no such rule")
        }
        fatalError("Can't resolve types correctly for invoking code block for rule number \(ruleNumber)")
    }

    private func yySymbolOnStack(distanceFromTop: Int) -> CitronSymbol {
        assert(yyStack.count > distanceFromTop)
        return yyStack[yyStack.count - 1 - distanceFromTop].symbol
    }

    func yyUnwrapResultFromSymbol(_ symbol: CitronSymbol) -> CitronResult {
        if case .yy11(let result) = symbol {
            return result
        } else {
            fatalError("Unexpected mismatch in result type")
        }
    }

    // Error capturing

    typealias CitronErrorCaptureDelegate = _ParenthesizedQueryParserCitronErrorCaptureDelegate

    weak var errorCaptureDelegate: CitronErrorCaptureDelegate? = nil

    let yyErrorCaptureSymbolNumbersForState: [CitronStateNumber:[CitronSymbolNumber]] = [:]
    let yyCanErrorCapture: Bool = false
    let yyErrorCaptureDirectives: [CitronSymbolNumber:(endAfter:[[CitronTokenCode]],endBefore:[CitronTokenCode])] = [:]
    let yyErrorCaptureEndBeforeTokens: Set<CitronSymbolNumber> = []

    let yyErrorCaptureEndAfterSequenceEndingTokens: Set<CitronSymbolNumber> = []

    func yyShouldSaveErrorForCapturing(error: Error) -> Bool {
        fatalError("This parser was not generated with error capturing information")
    }

    func yyCaptureError(on symbolCode: CitronNonTerminalCode, error: Error, state: CitronErrorCaptureState) -> CitronSymbol? {
        fatalError("This parser was not generated with error capturing information")
    }

    func yySymbolContent(_ symbol: CitronSymbol) -> Any { return symbol.typeErasedContent() }

    let yyStartSymbolNumber: CitronSymbolNumber = 6
    let yyEndStateNumber: CitronStateNumber = 9

    var yyErrorCaptureSavedError: (error: Error, isLexerError: Bool)? = nil
    var yyErrorCaptureTokensSinceError: [(token: CitronToken, tokenCode: CitronTokenCode)] = []
    var yyErrorCaptureStackIndices: [Int] = []
    var yyErrorCaptureStartSymbolStackIndex: Int? = nil

    var numberOfCapturedErrors: Int = 0
}

protocol _ParenthesizedQueryParserCitronErrorCaptureDelegate : AnyObject {
    func shouldSaveErrorForCapturing(error: Error) -> Bool
}

extension _ParenthesizedQueryParserCitronErrorCaptureDelegate {
    func shouldSaveErrorForCapturing(error: Error) -> Bool {
        return true
    }
}

// Ability to use == to compare CitronSymbolCode with CitronTokenCode / CitronNonTerminalCode

extension ParenthesizedQueryParser.CitronSymbolCode {
    static func == (a: ParenthesizedQueryParser.CitronSymbolCode, b: ParenthesizedQueryParser.CitronTokenCode) -> Bool {
        guard case let .token(code) = a else { return false }
        return (code == b)
    }
    static func == (a: ParenthesizedQueryParser.CitronTokenCode, b: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        guard case let .token(code) = b else { return false }
        return (code == a)
    }
    static func == (a: ParenthesizedQueryParser.CitronSymbolCode, b: ParenthesizedQueryParser.CitronNonTerminalCode) -> Bool {
        guard case let .nonterminal(code) = a else { return false }
        return (code == b)
    }
    static func == (a: ParenthesizedQueryParser.CitronNonTerminalCode, b: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        guard case let .nonterminal(code) = b else { return false }
        return (code == a)
    }
}

// Ability to use switch (symbolCode) { case .tokenCode: ...; case .nonterminalCode: ... }

extension ParenthesizedQueryParser.CitronSymbolCode {
    static func ~= (pattern: ParenthesizedQueryParser.CitronTokenCode, value: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
    static func ~= (pattern: ParenthesizedQueryParser.CitronNonTerminalCode, value: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
}
