// This file is automatically generated by Citron version 2.0.
//
// The parser class defined below conforms to the CitronParser protocol
// defined in CitronParser.swift. 
// 
// The authors of Citron disclaim copyright to the source code in this file.

// Parser class

class ParenthesizedQueryParser: CitronParser {

    // Types

    typealias CitronSymbolNumber = UInt8
    typealias CitronStateNumber = UInt8
    typealias CitronRuleNumber = UInt8

    enum CitronTokenCode: CitronSymbolNumber {
      case Or                             =   1
      case And                            =   2
      case Verbatim                       =   3
      case OpenParen                      =   4
      case CloseParen                     =   5
    }

    enum CitronNonTerminalCode: CitronSymbolNumber {
      case query                          =   6
      case disjunction                    =   7
      case conjunction                    =   8
      case term                           =   9
    }

    enum CitronSymbolCode : RawRepresentable, Equatable {
        case token(CitronTokenCode)
        case nonterminal(CitronNonTerminalCode)
        case endOfInput

        init(_ token: CitronTokenCode) { self = .token(token) }
        init(_ nonterminal: CitronNonTerminalCode) { self = .nonterminal(nonterminal) }
        init(rawValue: CitronSymbolNumber) {
            if (rawValue == 0) {
                self = .endOfInput
            } else if (rawValue < 6) {
                self = .token(CitronTokenCode(rawValue: rawValue)!)
            } else if (rawValue < 10) {
                self = .nonterminal(CitronNonTerminalCode(rawValue: rawValue)!)
            } else {
                fatalError()
            }
        }

        typealias RawValue = CitronSymbolNumber
        var rawValue: CitronSymbolNumber {
            switch (self) {
            case .token(let t): return t.rawValue
            case .nonterminal(let nt): return nt.rawValue
            case .endOfInput: return 0
            }
        }
    }

    typealias CitronToken = ParenthesizedQueryTokenContent

    enum CitronSymbol {
        case yyBaseOfStack
        case yy0(CitronToken)
        case yy1(ParenthesizedQuery)

        func typeErasedContent() -> Any {
            switch (self) {
            case .yyBaseOfStack: fatalError()
            case .yy0(let value): return value as Any
            case .yy1(let value): return value as Any
            }
        }
    }

    typealias CitronResult = ParenthesizedQuery

    // Counts

    let yyNumberOfSymbols: Int = 10
    let yyNumberOfStates: Int = 8

    // Action tables

    let yyLookaheadAction: [(CitronSymbolNumber, CitronParsingAction)] = [
/*   0 */  ( 6, .ACCEPT),   ( 7, .SH( 5)), ( 8, .SH( 6)), ( 9, .RD( 3)), ( 7, .SH( 4)),
/*   5 */  ( 8, .SH( 6)), ( 9, .RD( 3)), ( 3, .SR( 5)), ( 4, .SH( 1)), ( 8, .SH( 7)),
/*  10 */  ( 9, .RD( 3)), ( 1, .SH( 2)), ( 0, .RD( 0)), ( 1, .SH( 2)), ( 9, .RD( 4)),
/*  15 */  ( 5, .SR( 6)), ( 2, .SH( 3)),
    ]

    let yyShiftUseDefault: Int = 17
    let yyShiftOffsetMin: Int = 0
    let yyShiftOffsetMax: Int = 14
    let yyShiftOffset: [Int] = [
        /*     0 */     4,    4,    4,    4,   10,   12,   14,   14,
    ]

    let yyReduceUseDefault: Int = -7
    let yyReduceOffsetMin: Int =   -6
    let yyReduceOffsetMax: Int =   5
    let yyReduceOffset: [Int] = [
        /*     0 */    -6,   -3,    1,    5,
    ]

    let yyDefaultAction: [CitronParsingAction] = [
  /*     0 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*     5 */  .ERROR , .RD( 1), .RD( 2),
    ]

    // Fallback

    let yyHasFallback: Bool = false
    let yyFallback: [CitronSymbolNumber] = []

    // Wildcard

    let yyWildcard: CitronSymbolNumber? = nil

    // Rules

    let yyRuleInfo: [(lhs: CitronSymbolNumber, nrhs: UInt)] = [
        (lhs: 6, nrhs: 1),
        (lhs: 7, nrhs: 1),
        (lhs: 7, nrhs: 3),
        (lhs: 8, nrhs: 1),
        (lhs: 8, nrhs: 3),
        (lhs: 9, nrhs: 1),
        (lhs: 9, nrhs: 3),
    ]

    // Stack

    var yyStack: [(stateOrRule: CitronStateOrRule , symbolCode: CitronSymbolNumber, symbol: CitronSymbol)]  = [
        (stateOrRule: .state(0), symbolCode: 0, symbol: .yyBaseOfStack)
    ]
    var maxStackSize: Int? = nil
    var maxAttainedStackSize: Int = 0

    // Tracing

    var isTracingEnabled: Bool = false
    var isTracingPrintsSymbolValues: Bool = false
    var isTracingPrintsTokenValues: Bool = false
    let yySymbolName: [String] = [
    /*  0 */ "$",
    /*  1 */ "Or",
    /*  2 */ "And",
    /*  3 */ "Verbatim",
    /*  4 */ "OpenParen",
    /*  5 */ "CloseParen",
    /*  6 */ "query",
    /*  7 */ "disjunction",
    /*  8 */ "conjunction",
    /*  9 */ "term",
    ]
    let yyRuleText: [String] = [
        /*   0 */ "query ::= disjunction(d)",
        /*   1 */ "disjunction ::= conjunction(c)",
        /*   2 */ "disjunction ::= disjunction(d) Or conjunction(c)",
        /*   3 */ "conjunction ::= term(t)",
        /*   4 */ "conjunction ::= conjunction(c) And term(t)",
        /*   5 */ "term ::= Verbatim(v)",
        /*   6 */ "term ::= OpenParen(l) disjunction(q) CloseParen(r)",
    ]

    // Function definitions

    func yyTokenToSymbol(_ token: CitronToken) -> CitronSymbol {
        return .yy0(token)
    }

    func yyInvokeCodeBlockForRule(ruleNumber: CitronRuleNumber) throws -> CitronSymbol {
        switch (ruleNumber) {
        case 0: /* query ::= disjunction(d) */
            func codeBlockForRule0(d: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 6)
 d 
#sourceLocation()
}
            if case .yy1(let d) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule0(d: d))
            }
        case 1: /* disjunction ::= conjunction(c) */
            func codeBlockForRule1(c: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 9)
 c 
#sourceLocation()
}
            if case .yy1(let c) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule1(c: c))
            }
        case 2: /* disjunction ::= disjunction(d) Or conjunction(c) */
            func codeBlockForRule2(d: ParenthesizedQuery, c: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 10)

    .init(range: d.range.lowerBound..<c.range.upperBound, filters: d.filters + c.filters)

#sourceLocation()
}
            if case .yy1(let d) = yySymbolOnStack(distanceFromTop: 2),
               case .yy1(let c) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule2(d: d, c: c))
            }
        case 3: /* conjunction ::= term(t) */
            func codeBlockForRule3(t: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 19)
 t 
#sourceLocation()
}
            if case .yy1(let t) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule3(t: t))
            }
        case 4: /* conjunction ::= conjunction(c) And term(t) */
            func codeBlockForRule4(c: ParenthesizedQuery, t: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 20)

    .init(range: c.range.lowerBound..<t.range.upperBound, filters: c.filters + t.filters)

#sourceLocation()
}
            if case .yy1(let c) = yySymbolOnStack(distanceFromTop: 2),
               case .yy1(let t) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule4(c: c, t: t))
            }
        case 5: /* term ::= Verbatim(v) */
            func codeBlockForRule5(v: ParenthesizedQueryTokenContent) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 29)

    .init(range: v.range, filters: [v.range])

#sourceLocation()
}
            if case .yy0(let v) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule5(v: v))
            }
        case 6: /* term ::= OpenParen(l) disjunction(q) CloseParen(r) */
            func codeBlockForRule6(l: ParenthesizedQueryTokenContent, q: ParenthesizedQuery, r: ParenthesizedQueryTokenContent) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 32)

    .init(range: l.range.lowerBound..<r.range.upperBound, filters: q.filters)

#sourceLocation()
}
            if case .yy0(let l) = yySymbolOnStack(distanceFromTop: 2),
               case .yy1(let q) = yySymbolOnStack(distanceFromTop: 1),
               case .yy0(let r) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule6(l: l, q: q, r: r))
            }
        default:
            fatalError("Can't invoke code block for rule number \(ruleNumber) - no such rule")
        }
        fatalError("Can't resolve types correctly for invoking code block for rule number \(ruleNumber)")
    }

    private func yySymbolOnStack(distanceFromTop: Int) -> CitronSymbol {
        assert(yyStack.count > distanceFromTop)
        return yyStack[yyStack.count - 1 - distanceFromTop].symbol
    }

    func yyUnwrapResultFromSymbol(_ symbol: CitronSymbol) -> CitronResult {
        if case .yy1(let result) = symbol {
            return result
        } else {
            fatalError("Unexpected mismatch in result type")
        }
    }

    // Error capturing

    typealias CitronErrorCaptureDelegate = _ParenthesizedQueryParserCitronErrorCaptureDelegate

    weak var errorCaptureDelegate: CitronErrorCaptureDelegate? = nil

    let yyErrorCaptureSymbolNumbersForState: [CitronStateNumber:[CitronSymbolNumber]] = [:]
    let yyCanErrorCapture: Bool = false
    let yyErrorCaptureDirectives: [CitronSymbolNumber:(endAfter:[[CitronTokenCode]],endBefore:[CitronTokenCode])] = [:]
    let yyErrorCaptureEndBeforeTokens: Set<CitronSymbolNumber> = []

    let yyErrorCaptureEndAfterSequenceEndingTokens: Set<CitronSymbolNumber> = []

    func yyShouldSaveErrorForCapturing(error: Error) -> Bool {
        fatalError("This parser was not generated with error capturing information")
    }

    func yyCaptureError(on symbolCode: CitronNonTerminalCode, error: Error, state: CitronErrorCaptureState) -> CitronSymbol? {
        fatalError("This parser was not generated with error capturing information")
    }

    func yySymbolContent(_ symbol: CitronSymbol) -> Any { return symbol.typeErasedContent() }

    let yyStartSymbolNumber: CitronSymbolNumber = 6
    let yyEndStateNumber: CitronStateNumber = 5

    var yyErrorCaptureSavedError: (error: Error, isLexerError: Bool)? = nil
    var yyErrorCaptureTokensSinceError: [(token: CitronToken, tokenCode: CitronTokenCode)] = []
    var yyErrorCaptureStackIndices: [Int] = []
    var yyErrorCaptureStartSymbolStackIndex: Int? = nil

    var numberOfCapturedErrors: Int = 0
}

protocol _ParenthesizedQueryParserCitronErrorCaptureDelegate : AnyObject {
    func shouldSaveErrorForCapturing(error: Error) -> Bool
}

extension _ParenthesizedQueryParserCitronErrorCaptureDelegate {
    func shouldSaveErrorForCapturing(error: Error) -> Bool {
        return true
    }
}

// Ability to use == to compare CitronSymbolCode with CitronTokenCode / CitronNonTerminalCode

extension ParenthesizedQueryParser.CitronSymbolCode {
    static func == (a: ParenthesizedQueryParser.CitronSymbolCode, b: ParenthesizedQueryParser.CitronTokenCode) -> Bool {
        guard case let .token(code) = a else { return false }
        return (code == b)
    }
    static func == (a: ParenthesizedQueryParser.CitronTokenCode, b: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        guard case let .token(code) = b else { return false }
        return (code == a)
    }
    static func == (a: ParenthesizedQueryParser.CitronSymbolCode, b: ParenthesizedQueryParser.CitronNonTerminalCode) -> Bool {
        guard case let .nonterminal(code) = a else { return false }
        return (code == b)
    }
    static func == (a: ParenthesizedQueryParser.CitronNonTerminalCode, b: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        guard case let .nonterminal(code) = b else { return false }
        return (code == a)
    }
}

// Ability to use switch (symbolCode) { case .tokenCode: ...; case .nonterminalCode: ... }

extension ParenthesizedQueryParser.CitronSymbolCode {
    static func ~= (pattern: ParenthesizedQueryParser.CitronTokenCode, value: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
    static func ~= (pattern: ParenthesizedQueryParser.CitronNonTerminalCode, value: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
}
