// This file is automatically generated by Citron version 2.0.
//
// The parser class defined below conforms to the CitronParser protocol
// defined in CitronParser.swift. 
// 
// The authors of Citron disclaim copyright to the source code in this file.

// Parser class

class ParenthesizedQueryParser: CitronParser {

    // Types

    typealias CitronSymbolNumber = UInt8
    typealias CitronStateNumber = UInt8
    typealias CitronRuleNumber = UInt8

    enum CitronTokenCode: CitronSymbolNumber {
      case Or                             =   1
      case Verbatim                       =   2
      case And                            =   3
      case CloseParen                     =   4
      case OpenParen                      =   5
    }

    enum CitronNonTerminalCode: CitronSymbolNumber {
      case query                          =   6
      case disjunction                    =   7
      case conjunction                    =   8
      case parenthesized                  =   9
    }

    enum CitronSymbolCode : RawRepresentable, Equatable {
        case token(CitronTokenCode)
        case nonterminal(CitronNonTerminalCode)
        case endOfInput

        init(_ token: CitronTokenCode) { self = .token(token) }
        init(_ nonterminal: CitronNonTerminalCode) { self = .nonterminal(nonterminal) }
        init(rawValue: CitronSymbolNumber) {
            if (rawValue == 0) {
                self = .endOfInput
            } else if (rawValue < 6) {
                self = .token(CitronTokenCode(rawValue: rawValue)!)
            } else if (rawValue < 10) {
                self = .nonterminal(CitronNonTerminalCode(rawValue: rawValue)!)
            } else {
                fatalError()
            }
        }

        typealias RawValue = CitronSymbolNumber
        var rawValue: CitronSymbolNumber {
            switch (self) {
            case .token(let t): return t.rawValue
            case .nonterminal(let nt): return nt.rawValue
            case .endOfInput: return 0
            }
        }
    }

    typealias CitronToken = ParenthesizedQueryTokenContent

    enum CitronSymbol {
        case yyBaseOfStack
        case yy0(CitronToken)
        case yy1(ParenthesizedQuery)

        func typeErasedContent() -> Any {
            switch (self) {
            case .yyBaseOfStack: fatalError()
            case .yy0(let value): return value as Any
            case .yy1(let value): return value as Any
            }
        }
    }

    typealias CitronResult = ParenthesizedQuery

    // Counts

    let yyNumberOfSymbols: Int = 10
    let yyNumberOfStates: Int = 8

    // Action tables

    let yyLookaheadAction: [(CitronSymbolNumber, CitronParsingAction)] = [
/*   0 */  ( 6, .ACCEPT),   ( 7, .SH( 5)), ( 8, .SH( 6)), ( 9, .RD( 4)), ( 7, .SH( 4)),
/*   5 */  ( 8, .SH( 6)), ( 9, .RD( 4)), ( 2, .SR( 3)), ( 8, .SH( 7)), ( 9, .RD( 4)),
/*  10 */  ( 5, .SH( 1)), ( 2, .SR( 5)), ( 1, .SH( 2)), ( 9, .RD( 6)), ( 5, .SH( 1)),
/*  15 */  ( 4, .SR( 7)), ( 0, .RD( 0)), ( 1, .SH( 2)), ( 3, .SH( 3)),
    ]

    let yyShiftUseDefault: Int = 19
    let yyShiftOffsetMin: Int = 0
    let yyShiftOffsetMax: Int = 16
    let yyShiftOffset: [Int] = [
        /*     0 */     5,    5,    5,    9,   11,   16,   15,   15,
    ]

    let yyReduceUseDefault: Int = -7
    let yyReduceOffsetMin: Int =   -6
    let yyReduceOffsetMax: Int =   4
    let yyReduceOffset: [Int] = [
        /*     0 */    -6,   -3,    0,    4,
    ]

    let yyDefaultAction: [CitronParsingAction] = [
  /*     0 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*     5 */  .ERROR , .RD( 1), .RD( 2),
    ]

    // Fallback

    let yyHasFallback: Bool = false
    let yyFallback: [CitronSymbolNumber] = []

    // Wildcard

    let yyWildcard: CitronSymbolNumber? = nil

    // Rules

    let yyRuleInfo: [(lhs: CitronSymbolNumber, nrhs: UInt)] = [
        (lhs: 6, nrhs: 1),
        (lhs: 7, nrhs: 1),
        (lhs: 7, nrhs: 3),
        (lhs: 8, nrhs: 1),
        (lhs: 8, nrhs: 1),
        (lhs: 8, nrhs: 3),
        (lhs: 8, nrhs: 3),
        (lhs: 9, nrhs: 3),
    ]

    // Stack

    var yyStack: [(stateOrRule: CitronStateOrRule , symbolCode: CitronSymbolNumber, symbol: CitronSymbol)]  = [
        (stateOrRule: .state(0), symbolCode: 0, symbol: .yyBaseOfStack)
    ]
    var maxStackSize: Int? = nil
    var maxAttainedStackSize: Int = 0

    // Tracing

    var isTracingEnabled: Bool = false
    var isTracingPrintsSymbolValues: Bool = false
    var isTracingPrintsTokenValues: Bool = false
    let yySymbolName: [String] = [
    /*  0 */ "$",
    /*  1 */ "Or",
    /*  2 */ "Verbatim",
    /*  3 */ "And",
    /*  4 */ "CloseParen",
    /*  5 */ "OpenParen",
    /*  6 */ "query",
    /*  7 */ "disjunction",
    /*  8 */ "conjunction",
    /*  9 */ "parenthesized",
    ]
    let yyRuleText: [String] = [
        /*   0 */ "query ::= disjunction(d)",
        /*   1 */ "disjunction ::= conjunction(c)",
        /*   2 */ "disjunction ::= disjunction(d) Or conjunction(c)",
        /*   3 */ "conjunction ::= Verbatim(range)",
        /*   4 */ "conjunction ::= parenthesized(p)",
        /*   5 */ "conjunction ::= conjunction(c) And Verbatim(range)",
        /*   6 */ "conjunction ::= conjunction(c) And parenthesized(p)",
        /*   7 */ "parenthesized ::= OpenParen(l) disjunction(q) CloseParen(r)",
    ]

    // Function definitions

    func yyTokenToSymbol(_ token: CitronToken) -> CitronSymbol {
        return .yy0(token)
    }

    func yyInvokeCodeBlockForRule(ruleNumber: CitronRuleNumber) throws -> CitronSymbol {
        switch (ruleNumber) {
        case 0: /* query ::= disjunction(d) */
            func codeBlockForRule0(d: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 7)
 d 
#sourceLocation()
}
            if case .yy1(let d) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule0(d: d))
            }
        case 1: /* disjunction ::= conjunction(c) */
            func codeBlockForRule1(c: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 11)
 c 
#sourceLocation()
}
            if case .yy1(let c) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule1(c: c))
            }
        case 2: /* disjunction ::= disjunction(d) Or conjunction(c) */
            func codeBlockForRule2(d: ParenthesizedQuery, c: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 12)

    .init(filters: d.filters + c.filters)

#sourceLocation()
}
            if case .yy1(let d) = yySymbolOnStack(distanceFromTop: 2),
               case .yy1(let c) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule2(d: d, c: c))
            }
        case 3: /* conjunction ::= Verbatim(range) */
            func codeBlockForRule3(range: ParenthesizedQueryTokenContent) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 18)

    .init(filters: [range])

#sourceLocation()
}
            if case .yy0(let range) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule3(range: range))
            }
        case 4: /* conjunction ::= parenthesized(p) */
            func codeBlockForRule4(p: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 21)
 p 
#sourceLocation()
}
            if case .yy1(let p) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule4(p: p))
            }
        case 5: /* conjunction ::= conjunction(c) And Verbatim(range) */
            func codeBlockForRule5(c: ParenthesizedQuery, range: ParenthesizedQueryTokenContent) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 22)

    .init(filters: c.filters + [range])

#sourceLocation()
}
            if case .yy1(let c) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let range) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule5(c: c, range: range))
            }
        case 6: /* conjunction ::= conjunction(c) And parenthesized(p) */
            func codeBlockForRule6(c: ParenthesizedQuery, p: ParenthesizedQuery) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 25)

    .init(filters: c.filters + p.filters)

#sourceLocation()
}
            if case .yy1(let c) = yySymbolOnStack(distanceFromTop: 2),
               case .yy1(let p) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule6(c: c, p: p))
            }
        case 7: /* parenthesized ::= OpenParen(l) disjunction(q) CloseParen(r) */
            func codeBlockForRule7(l: ParenthesizedQueryTokenContent, q: ParenthesizedQuery, r: ParenthesizedQueryTokenContent) throws -> ParenthesizedQuery {
#sourceLocation(file: "MagicCardSearch/Parser/ParenthesizedQuery/ParenthesizedQueryGrammar.y", line: 31)

    .init(filters: q.filters)

#sourceLocation()
}
            if case .yy0(let l) = yySymbolOnStack(distanceFromTop: 2),
               case .yy1(let q) = yySymbolOnStack(distanceFromTop: 1),
               case .yy0(let r) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy1(try codeBlockForRule7(l: l, q: q, r: r))
            }
        default:
            fatalError("Can't invoke code block for rule number \(ruleNumber) - no such rule")
        }
        fatalError("Can't resolve types correctly for invoking code block for rule number \(ruleNumber)")
    }

    private func yySymbolOnStack(distanceFromTop: Int) -> CitronSymbol {
        assert(yyStack.count > distanceFromTop)
        return yyStack[yyStack.count - 1 - distanceFromTop].symbol
    }

    func yyUnwrapResultFromSymbol(_ symbol: CitronSymbol) -> CitronResult {
        if case .yy1(let result) = symbol {
            return result
        } else {
            fatalError("Unexpected mismatch in result type")
        }
    }

    // Error capturing

    typealias CitronErrorCaptureDelegate = _ParenthesizedQueryParserCitronErrorCaptureDelegate

    weak var errorCaptureDelegate: CitronErrorCaptureDelegate? = nil

    let yyErrorCaptureSymbolNumbersForState: [CitronStateNumber:[CitronSymbolNumber]] = [
          0 : [6, 9],
          1 : [9],
          2 : [9],
          3 : [9],
    ]
    let yyCanErrorCapture: Bool = true
    let yyErrorCaptureDirectives: [CitronSymbolNumber:(endAfter:[[CitronTokenCode]],endBefore:[CitronTokenCode])] = [
         9 : (endAfter: [],
              endBefore: [.CloseParen, .Verbatim, .Or, .And])
    ]
    let yyErrorCaptureEndBeforeTokens: Set<CitronSymbolNumber> = [
        1, 2, 3, 4
    ]
    let yyErrorCaptureEndAfterSequenceEndingTokens: Set<CitronSymbolNumber> = [
        
    ]

    func yyShouldSaveErrorForCapturing(error: Error) -> Bool {
        guard let delegate = errorCaptureDelegate else {
            print("Error capture: Not saving error for capturing because errorCaptureDelegate is not set")
            return false
        }
        return delegate.shouldSaveErrorForCapturing(error: error)
    }

    func yyCaptureError(on symbolCode: CitronNonTerminalCode, error: Error, state: CitronErrorCaptureState) -> CitronSymbol? {
        guard let delegate = errorCaptureDelegate else {
            print("Error capture: Not capturing error because errorCaptureDelegate is not set")
            return nil
        }

        switch (symbolCode) {
        case .query:
            let delegateResponse = delegate.shouldCaptureErrorOnQuery(state: state, error: error)
            switch (delegateResponse) {
            case .captureAs(let symbol):
                return .yy1(symbol)
            case .dontCapture:
                return nil
            }
        case .parenthesized:
            let delegateResponse = delegate.shouldCaptureErrorOnParenthesized(state: state, error: error)
            switch (delegateResponse) {
            case .captureAs(let symbol):
                return .yy1(symbol)
            case .dontCapture:
                return nil
            }
        default:
            fatalError("yyCaptureError: Symbol code \(symbolCode) is not an error capturing symbol code")
        }
    }

    func yySymbolContent(_ symbol: CitronSymbol) -> Any { return symbol.typeErasedContent() }

    let yyStartSymbolNumber: CitronSymbolNumber = 6
    let yyEndStateNumber: CitronStateNumber = 5

    var yyErrorCaptureSavedError: (error: Error, isLexerError: Bool)? = nil
    var yyErrorCaptureTokensSinceError: [(token: CitronToken, tokenCode: CitronTokenCode)] = []
    var yyErrorCaptureStackIndices: [Int] = []
    var yyErrorCaptureStartSymbolStackIndex: Int? = nil

    var numberOfCapturedErrors: Int = 0
}

protocol _ParenthesizedQueryParserCitronErrorCaptureDelegate : AnyObject {
    func shouldSaveErrorForCapturing(error: Error) -> Bool

    /* query */
    func shouldCaptureErrorOnQuery(state: ParenthesizedQueryParser.CitronErrorCaptureState,
        error: Error) -> CitronErrorCaptureResponse<ParenthesizedQuery>

    /* parenthesized */
    func shouldCaptureErrorOnParenthesized(state: ParenthesizedQueryParser.CitronErrorCaptureState,
        error: Error) -> CitronErrorCaptureResponse<ParenthesizedQuery>
}

extension _ParenthesizedQueryParserCitronErrorCaptureDelegate {
    func shouldSaveErrorForCapturing(error: Error) -> Bool {
        return true
    }
}

// Ability to use == to compare CitronSymbolCode with CitronTokenCode / CitronNonTerminalCode

extension ParenthesizedQueryParser.CitronSymbolCode {
    static func == (a: ParenthesizedQueryParser.CitronSymbolCode, b: ParenthesizedQueryParser.CitronTokenCode) -> Bool {
        guard case let .token(code) = a else { return false }
        return (code == b)
    }
    static func == (a: ParenthesizedQueryParser.CitronTokenCode, b: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        guard case let .token(code) = b else { return false }
        return (code == a)
    }
    static func == (a: ParenthesizedQueryParser.CitronSymbolCode, b: ParenthesizedQueryParser.CitronNonTerminalCode) -> Bool {
        guard case let .nonterminal(code) = a else { return false }
        return (code == b)
    }
    static func == (a: ParenthesizedQueryParser.CitronNonTerminalCode, b: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        guard case let .nonterminal(code) = b else { return false }
        return (code == a)
    }
}

// Ability to use switch (symbolCode) { case .tokenCode: ...; case .nonterminalCode: ... }

extension ParenthesizedQueryParser.CitronSymbolCode {
    static func ~= (pattern: ParenthesizedQueryParser.CitronTokenCode, value: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
    static func ~= (pattern: ParenthesizedQueryParser.CitronNonTerminalCode, value: ParenthesizedQueryParser.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
}
