// This file is automatically generated by Citron version 2.0.
//
// The parser class defined below conforms to the CitronParser protocol
// defined in CitronParser.swift. 
// 
// The authors of Citron disclaim copyright to the source code in this file.

// Parser class

class MagicCardSearchGrammar: CitronParser {

    // Types

    typealias CitronSymbolNumber = UInt8
    typealias CitronStateNumber = UInt8
    typealias CitronRuleNumber = UInt8

    enum CitronTokenCode: CitronSymbolNumber {
      case Equal                          =   1
      case Colon                          =   2
      case LessThan                       =   3
      case LessThanOrEqual                =   4
      case GreaterThan                    =   5
      case GreaterThanOrEqual             =   6
      case Text                           =   7
    }

    enum CitronNonTerminalCode: CitronSymbolNumber {
      case filter                         =   8
      case text                           =   9
    }

    enum CitronSymbolCode : RawRepresentable, Equatable {
        case token(CitronTokenCode)
        case nonterminal(CitronNonTerminalCode)
        case endOfInput

        init(_ token: CitronTokenCode) { self = .token(token) }
        init(_ nonterminal: CitronNonTerminalCode) { self = .nonterminal(nonterminal) }
        init(rawValue: CitronSymbolNumber) {
            if (rawValue == 0) {
                self = .endOfInput
            } else if (rawValue < 8) {
                self = .token(CitronTokenCode(rawValue: rawValue)!)
            } else if (rawValue < 10) {
                self = .nonterminal(CitronNonTerminalCode(rawValue: rawValue)!)
            } else {
                fatalError()
            }
        }

        typealias RawValue = CitronSymbolNumber
        var rawValue: CitronSymbolNumber {
            switch (self) {
            case .token(let t): return t.rawValue
            case .nonterminal(let nt): return nt.rawValue
            case .endOfInput: return 0
            }
        }
    }

    typealias CitronToken = Token

    enum CitronSymbol {
        case yyBaseOfStack
        case yy0(CitronToken)
        case yy4(String)
        case yy9(SearchFilter)

        func typeErasedContent() -> Any {
            switch (self) {
            case .yyBaseOfStack: fatalError()
            case .yy0(let value): return value as Any
            case .yy4(let value): return value as Any
            case .yy9(let value): return value as Any
            }
        }
    }

    typealias CitronResult = SearchFilter

    // Counts

    let yyNumberOfSymbols: Int = 10
    let yyNumberOfStates: Int = 14

    // Action tables

    let yyLookaheadAction: [(CitronSymbolNumber, CitronParsingAction)] = [
/*   0 */  ( 1, .SH( 6)), ( 2, .SH( 5)), ( 3, .SH( 4)), ( 4, .SH( 3)), ( 5, .SH( 2)),
/*   5 */  ( 6, .SH( 1)), ( 8, .ACCEPT),   ( 9, .SH( 7)), ( 7, .SR( 6)), ( 9, .SH( 8)),
/*  10 */  ( 0, .RD( 5)), ( 9, .SH( 9)), ( 9, .SH(10)), ( 9, .SH(11)), ( 9, .SH(12)),
/*  15 */  ( 9, .SH(13)), ( 0, .RD( 4)), ( 0, .RD( 3)), ( 0, .RD( 2)), ( 0, .RD( 1)),
/*  20 */  ( 0, .RD( 0)),
    ]

    let yyShiftUseDefault: Int = 21
    let yyShiftOffsetMin: Int = -1
    let yyShiftOffsetMax: Int = 20
    let yyShiftOffset: [Int] = [
        /*     0 */     1,    1,    1,    1,    1,    1,    1,   -1,   10,   16,
        /*    10 */    17,   18,   19,   20,
    ]

    let yyReduceUseDefault: Int = -3
    let yyReduceOffsetMin: Int =   -2
    let yyReduceOffsetMax: Int =   6
    let yyReduceOffset: [Int] = [
        /*     0 */    -2,    0,    2,    3,    4,    5,    6,
    ]

    let yyDefaultAction: [CitronParsingAction] = [
  /*     0 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*     5 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*    10 */  .ERROR , .ERROR , .ERROR , .ERROR ,
    ]

    // Fallback

    let yyHasFallback: Bool = false
    let yyFallback: [CitronSymbolNumber] = []

    // Wildcard

    let yyWildcard: CitronSymbolNumber? = nil

    // Rules

    let yyRuleInfo: [(lhs: CitronSymbolNumber, nrhs: UInt)] = [
        (lhs: 8, nrhs: 3),
        (lhs: 8, nrhs: 3),
        (lhs: 8, nrhs: 3),
        (lhs: 8, nrhs: 3),
        (lhs: 8, nrhs: 3),
        (lhs: 8, nrhs: 3),
        (lhs: 9, nrhs: 1),
    ]

    // Stack

    var yyStack: [(stateOrRule: CitronStateOrRule , symbolCode: CitronSymbolNumber, symbol: CitronSymbol)]  = [
        (stateOrRule: .state(0), symbolCode: 0, symbol: .yyBaseOfStack)
    ]
    var maxStackSize: Int? = nil
    var maxAttainedStackSize: Int = 0

    // Tracing

    var isTracingEnabled: Bool = false
    var isTracingPrintsSymbolValues: Bool = false
    var isTracingPrintsTokenValues: Bool = false
    let yySymbolName: [String] = [
    /*  0 */ "$",
    /*  1 */ "Equal",
    /*  2 */ "Colon",
    /*  3 */ "LessThan",
    /*  4 */ "LessThanOrEqual",
    /*  5 */ "GreaterThan",
    /*  6 */ "GreaterThanOrEqual",
    /*  7 */ "Text",
    /*  8 */ "filter",
    /*  9 */ "text",
    ]
    let yyRuleText: [String] = [
        /*   0 */ "filter ::= text(kind) Equal text(value)",
        /*   1 */ "filter ::= text(kind) Colon text(value)",
        /*   2 */ "filter ::= text(kind) LessThan text(value)",
        /*   3 */ "filter ::= text(kind) LessThanOrEqual text(value)",
        /*   4 */ "filter ::= text(kind) GreaterThan text(value)",
        /*   5 */ "filter ::= text(kind) GreaterThanOrEqual text(value)",
        /*   6 */ "text ::= Text(x)",
    ]

    // Function definitions

    func yyTokenToSymbol(_ token: CitronToken) -> CitronSymbol {
        return .yy0(token)
    }

    func yyInvokeCodeBlockForRule(ruleNumber: CitronRuleNumber) throws -> CitronSymbol {
        switch (ruleNumber) {
        case 0: /* filter ::= text(kind) Equal text(value) */
            func codeBlockForRule0(kind: String, value: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 6)

    return SearchFilter(kind, value)

#sourceLocation()
}
            if case .yy4(let kind) = yySymbolOnStack(distanceFromTop: 2),
               case .yy4(let value) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy9(try codeBlockForRule0(kind: kind, value: value))
            }
        case 1: /* filter ::= text(kind) Colon text(value) */
            func codeBlockForRule1(kind: String, value: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 9)

return SearchFilter(kind, value)

#sourceLocation()
}
            if case .yy4(let kind) = yySymbolOnStack(distanceFromTop: 2),
               case .yy4(let value) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy9(try codeBlockForRule1(kind: kind, value: value))
            }
        case 2: /* filter ::= text(kind) LessThan text(value) */
            func codeBlockForRule2(kind: String, value: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 12)

    return SearchFilter(kind, value)

#sourceLocation()
}
            if case .yy4(let kind) = yySymbolOnStack(distanceFromTop: 2),
               case .yy4(let value) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy9(try codeBlockForRule2(kind: kind, value: value))
            }
        case 3: /* filter ::= text(kind) LessThanOrEqual text(value) */
            func codeBlockForRule3(kind: String, value: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 15)

    return SearchFilter(kind, value)

#sourceLocation()
}
            if case .yy4(let kind) = yySymbolOnStack(distanceFromTop: 2),
               case .yy4(let value) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy9(try codeBlockForRule3(kind: kind, value: value))
            }
        case 4: /* filter ::= text(kind) GreaterThan text(value) */
            func codeBlockForRule4(kind: String, value: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 18)

    return SearchFilter(kind, value)

#sourceLocation()
}
            if case .yy4(let kind) = yySymbolOnStack(distanceFromTop: 2),
               case .yy4(let value) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy9(try codeBlockForRule4(kind: kind, value: value))
            }
        case 5: /* filter ::= text(kind) GreaterThanOrEqual text(value) */
            func codeBlockForRule5(kind: String, value: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 21)

    return SearchFilter(kind, value)

#sourceLocation()
}
            if case .yy4(let kind) = yySymbolOnStack(distanceFromTop: 2),
               case .yy4(let value) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy9(try codeBlockForRule5(kind: kind, value: value))
            }
        case 6: /* text ::= Text(x) */
            func codeBlockForRule6(x: Token) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 27)

    if case .text(let text) = x {
        return text
    } else {
        preconditionFailure("lexer did not return Token.text for the Text token")
    }

#sourceLocation()
}
            if case .yy0(let x) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy4(try codeBlockForRule6(x: x))
            }
        default:
            fatalError("Can't invoke code block for rule number \(ruleNumber) - no such rule")
        }
        fatalError("Can't resolve types correctly for invoking code block for rule number \(ruleNumber)")
    }

    private func yySymbolOnStack(distanceFromTop: Int) -> CitronSymbol {
        assert(yyStack.count > distanceFromTop)
        return yyStack[yyStack.count - 1 - distanceFromTop].symbol
    }

    func yyUnwrapResultFromSymbol(_ symbol: CitronSymbol) -> CitronResult {
        if case .yy9(let result) = symbol {
            return result
        } else {
            fatalError("Unexpected mismatch in result type")
        }
    }

    // Error capturing

    typealias CitronErrorCaptureDelegate = _MagicCardSearchGrammarCitronErrorCaptureDelegate

    weak var errorCaptureDelegate: CitronErrorCaptureDelegate? = nil

    let yyErrorCaptureSymbolNumbersForState: [CitronStateNumber:[CitronSymbolNumber]] = [:]
    let yyCanErrorCapture: Bool = false
    let yyErrorCaptureDirectives: [CitronSymbolNumber:(endAfter:[[CitronTokenCode]],endBefore:[CitronTokenCode])] = [:]
    let yyErrorCaptureEndBeforeTokens: Set<CitronSymbolNumber> = []

    let yyErrorCaptureEndAfterSequenceEndingTokens: Set<CitronSymbolNumber> = []

    func yyShouldSaveErrorForCapturing(error: Error) -> Bool {
        fatalError("This parser was not generated with error capturing information")
    }

    func yyCaptureError(on symbolCode: CitronNonTerminalCode, error: Error, state: CitronErrorCaptureState) -> CitronSymbol? {
        fatalError("This parser was not generated with error capturing information")
    }

    func yySymbolContent(_ symbol: CitronSymbol) -> Any { return symbol.typeErasedContent() }

    let yyStartSymbolNumber: CitronSymbolNumber = 8
    let yyEndStateNumber: CitronStateNumber = 8

    var yyErrorCaptureSavedError: (error: Error, isLexerError: Bool)? = nil
    var yyErrorCaptureTokensSinceError: [(token: CitronToken, tokenCode: CitronTokenCode)] = []
    var yyErrorCaptureStackIndices: [Int] = []
    var yyErrorCaptureStartSymbolStackIndex: Int? = nil

    var numberOfCapturedErrors: Int = 0
}

protocol _MagicCardSearchGrammarCitronErrorCaptureDelegate : AnyObject {
    func shouldSaveErrorForCapturing(error: Error) -> Bool
}

extension _MagicCardSearchGrammarCitronErrorCaptureDelegate {
    func shouldSaveErrorForCapturing(error: Error) -> Bool {
        return true
    }
}

// Ability to use == to compare CitronSymbolCode with CitronTokenCode / CitronNonTerminalCode

extension MagicCardSearchGrammar.CitronSymbolCode {
    static func == (a: MagicCardSearchGrammar.CitronSymbolCode, b: MagicCardSearchGrammar.CitronTokenCode) -> Bool {
        guard case let .token(code) = a else { return false }
        return (code == b)
    }
    static func == (a: MagicCardSearchGrammar.CitronTokenCode, b: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        guard case let .token(code) = b else { return false }
        return (code == a)
    }
    static func == (a: MagicCardSearchGrammar.CitronSymbolCode, b: MagicCardSearchGrammar.CitronNonTerminalCode) -> Bool {
        guard case let .nonterminal(code) = a else { return false }
        return (code == b)
    }
    static func == (a: MagicCardSearchGrammar.CitronNonTerminalCode, b: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        guard case let .nonterminal(code) = b else { return false }
        return (code == a)
    }
}

// Ability to use switch (symbolCode) { case .tokenCode: ...; case .nonterminalCode: ... }

extension MagicCardSearchGrammar.CitronSymbolCode {
    static func ~= (pattern: MagicCardSearchGrammar.CitronTokenCode, value: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
    static func ~= (pattern: MagicCardSearchGrammar.CitronNonTerminalCode, value: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
}
