// This file is automatically generated by Citron version 2.0.
//
// The parser class defined below conforms to the CitronParser protocol
// defined in CitronParser.swift. 
// 
// The authors of Citron disclaim copyright to the source code in this file.

// Parser class

class MagicCardSearchGrammar: CitronParser {

    // Types

    typealias CitronSymbolNumber = UInt8
    typealias CitronStateNumber = UInt8
    typealias CitronRuleNumber = UInt8

    enum CitronTokenCode: CitronSymbolNumber {
      case SingleQuote                    =   1
      case DoubleQuote                    =   2
      case Whitespace                     =   3
      case Comparison                     =   4
      case Term                           =   5
      case Including                      =   6
      case Equal                          =   7
      case NotEqual                       =   8
      case LessThan                       =   9
      case LessThanOrEqual                =  10
      case GreaterThan                    =  11
      case GreaterThanOrEqual             =  12
    }

    enum CitronNonTerminalCode: CitronSymbolNumber {
      case filter                         =  13
      case term                           =  14
      case comparison                     =  15
      case terms_double_quote             =  16
      case terms_single_quote             =  17
      case terms_bare                     =  18
    }

    enum CitronSymbolCode : RawRepresentable, Equatable {
        case token(CitronTokenCode)
        case nonterminal(CitronNonTerminalCode)
        case endOfInput

        init(_ token: CitronTokenCode) { self = .token(token) }
        init(_ nonterminal: CitronNonTerminalCode) { self = .nonterminal(nonterminal) }
        init(rawValue: CitronSymbolNumber) {
            if (rawValue == 0) {
                self = .endOfInput
            } else if (rawValue < 13) {
                self = .token(CitronTokenCode(rawValue: rawValue)!)
            } else if (rawValue < 19) {
                self = .nonterminal(CitronNonTerminalCode(rawValue: rawValue)!)
            } else {
                fatalError()
            }
        }

        typealias RawValue = CitronSymbolNumber
        var rawValue: CitronSymbolNumber {
            switch (self) {
            case .token(let t): return t.rawValue
            case .nonterminal(let nt): return nt.rawValue
            case .endOfInput: return 0
            }
        }
    }

    typealias CitronToken = Token

    enum CitronSymbol {
        case yyBaseOfStack
        case yy0(CitronToken)
        case yy3(SearchFilter)
        case yy26(Comparison)
        case yy36(String)

        func typeErasedContent() -> Any {
            switch (self) {
            case .yyBaseOfStack: fatalError()
            case .yy0(let value): return value as Any
            case .yy3(let value): return value as Any
            case .yy26(let value): return value as Any
            case .yy36(let value): return value as Any
            }
        }
    }

    typealias CitronResult = SearchFilter

    // Counts

    let yyNumberOfSymbols: Int = 19
    let yyNumberOfStates: Int = 30

    // Action tables

    let yyLookaheadAction: [(CitronSymbolNumber, CitronParsingAction)] = [
/*   0 */  ( 1, .SH( 5)), ( 2, .SH( 4)), ( 3, .SH( 6)), ( 4, .SH( 3)), (15, .SH(16)),
/*   5 */  ( 6, .SR(20)), ( 7, .SR(21)), ( 8, .SR(22)), ( 9, .SR(23)), (10, .SR(24)),
/*  10 */  (11, .SR(25)), (12, .SR(26)), ( 1, .SH( 5)), ( 2, .SH( 4)), ( 3, .SH( 6)),
/*  15 */  ( 4, .SH( 3)), ( 1, .SH( 2)), ( 2, .SH( 1)), ( 5, .SR(19)), (14, .SH(29)),
/*  20 */  ( 5, .SR(19)), (13, .ACCEPT),   (14, .SH(15)), ( 1, .SH(14)), ( 2, .SH(10)),
/*  25 */  (19, .RD( 2)), (18, .SH(20)), ( 5, .SR(19)), ( 1, .SH( 7)), ( 1, .SH(23)),
/*  30 */  ( 3, .SH( 9)), ( 4, .SH( 8)), (14, .SH(17)), ( 2, .SH(11)), ( 3, .SH(13)),
/*  35 */  ( 4, .SH(12)), (18, .RD(17)), (14, .SH(18)), (14, .SH(17)), (14, .SH(19)),
/*  40 */  (17, .SH(22)), (16, .SH(24)), (18, .RD(16)), (14, .SH(17)), ( 2, .SH(21)),
/*  45 */  ( 0, .RD( 3)), (14, .SH(17)), (18, .RD(15)), (14, .SH(18)), (14, .SH(18)),
/*  50 */  (18, .RD(14)), (17, .RD( 8)), (17, .RD( 7)), (14, .SH(18)), (14, .SH(18)),
/*  55 */  ( 0, .RD( 5)), (17, .RD( 6)), (17, .SH(26)), (14, .SH(19)), ( 0, .RD( 4)),
/*  60 */  (16, .RD(12)), (14, .SH(19)), (14, .SH(19)), (16, .RD(11)), (16, .RD(10)),
/*  65 */  (14, .SH(19)), ( 0, .RD( 2)), (16, .SH(28)), ( 0, .RD( 1)), ( 2, .SH(25)),
/*  70 */  ( 1, .SH(27)), ( 0, .RD( 0)),
    ]

    let yyShiftUseDefault: Int = 72
    let yyShiftOffsetMin: Int = -1
    let yyShiftOffsetMax: Int = 71
    let yyShiftOffset: [Int] = [
        /*     0 */    15,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        /*    10 */    13,   13,   13,   13,   13,   -1,   22,   11,   27,   31,
        /*    20 */    55,   59,   42,   45,   28,   66,   67,   68,   69,   71,
    ]

    let yyReduceUseDefault: Int = -12
    let yyReduceOffsetMin: Int =   -11
    let yyReduceOffsetMax: Int =   51
    let yyReduceOffset: [Int] = [
        /*     0 */     8,   23,   25,   18,   24,   29,   32,   34,   35,   39,
        /*    10 */    40,   44,   47,   48,   51,  -11,    5,
    ]

    let yyDefaultAction: [CitronParsingAction] = [
  /*     0 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*     5 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*    10 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*    15 */  .RD(18), .ERROR , .RD(18), .RD( 9), .RD(13),
  /*    20 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*    25 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
    ]

    // Fallback

    let yyHasFallback: Bool = false
    let yyFallback: [CitronSymbolNumber] = []

    // Wildcard

    let yyWildcard: CitronSymbolNumber? = nil

    // Rules

    let yyRuleInfo: [(lhs: CitronSymbolNumber, nrhs: UInt)] = [
        (lhs: 13, nrhs: 3),
        (lhs: 13, nrhs: 5),
        (lhs: 13, nrhs: 5),
        (lhs: 13, nrhs: 3),
        (lhs: 13, nrhs: 3),
        (lhs: 13, nrhs: 1),
        (lhs: 17, nrhs: 3),
        (lhs: 17, nrhs: 3),
        (lhs: 17, nrhs: 3),
        (lhs: 17, nrhs: 1),
        (lhs: 16, nrhs: 3),
        (lhs: 16, nrhs: 3),
        (lhs: 16, nrhs: 3),
        (lhs: 16, nrhs: 1),
        (lhs: 18, nrhs: 3),
        (lhs: 18, nrhs: 3),
        (lhs: 18, nrhs: 3),
        (lhs: 18, nrhs: 3),
        (lhs: 18, nrhs: 1),
        (lhs: 14, nrhs: 1),
        (lhs: 15, nrhs: 1),
        (lhs: 15, nrhs: 1),
        (lhs: 15, nrhs: 1),
        (lhs: 15, nrhs: 1),
        (lhs: 15, nrhs: 1),
        (lhs: 15, nrhs: 1),
        (lhs: 15, nrhs: 1),
    ]

    // Stack

    var yyStack: [(stateOrRule: CitronStateOrRule , symbolCode: CitronSymbolNumber, symbol: CitronSymbol)]  = [
        (stateOrRule: .state(0), symbolCode: 0, symbol: .yyBaseOfStack)
    ]
    var maxStackSize: Int? = nil
    var maxAttainedStackSize: Int = 0

    // Tracing

    var isTracingEnabled: Bool = false
    var isTracingPrintsSymbolValues: Bool = false
    var isTracingPrintsTokenValues: Bool = false
    let yySymbolName: [String] = [
    /*  0 */ "$",
    /*  1 */ "SingleQuote",
    /*  2 */ "DoubleQuote",
    /*  3 */ "Whitespace",
    /*  4 */ "Comparison",
    /*  5 */ "Term",
    /*  6 */ "Including",
    /*  7 */ "Equal",
    /*  8 */ "NotEqual",
    /*  9 */ "LessThan",
    /* 10 */ "LessThanOrEqual",
    /* 11 */ "GreaterThan",
    /* 12 */ "GreaterThanOrEqual",
    /* 13 */ "filter",
    /* 14 */ "term",
    /* 15 */ "comparison",
    /* 16 */ "terms_double_quote",
    /* 17 */ "terms_single_quote",
    /* 18 */ "terms_bare",
    ]
    let yyRuleText: [String] = [
        /*   0 */ "filter ::= term(k) comparison(c) term(v)",
        /*   1 */ "filter ::= term(k) comparison(c) SingleQuote terms_double_quote(v) SingleQuote",
        /*   2 */ "filter ::= term(k) comparison(c) DoubleQuote terms_single_quote(v) DoubleQuote",
        /*   3 */ "filter ::= SingleQuote terms_double_quote(v) SingleQuote",
        /*   4 */ "filter ::= DoubleQuote terms_single_quote(v) DoubleQuote",
        /*   5 */ "filter ::= terms_bare(v)",
        /*   6 */ "terms_single_quote ::= term(t) Whitespace(w) terms_single_quote(ts)",
        /*   7 */ "terms_single_quote ::= term(t) Comparison(c) terms_single_quote(ts)",
        /*   8 */ "terms_single_quote ::= term(t) SingleQuote terms_single_quote(ts)",
        /*   9 */ "terms_single_quote ::= term(t)",
        /*  10 */ "terms_double_quote ::= term(t) Whitespace(w) terms_double_quote(ts)",
        /*  11 */ "terms_double_quote ::= term(t) Comparison(c) terms_double_quote(ts)",
        /*  12 */ "terms_double_quote ::= term(t) DoubleQuote terms_double_quote(ts)",
        /*  13 */ "terms_double_quote ::= term(t)",
        /*  14 */ "terms_bare ::= term(t) Whitespace(w) terms_bare(ts)",
        /*  15 */ "terms_bare ::= term(t) SingleQuote terms_bare(ts)",
        /*  16 */ "terms_bare ::= term(t) DoubleQuote terms_bare(ts)",
        /*  17 */ "terms_bare ::= term(t) Comparison(c) terms_bare(ts)",
        /*  18 */ "terms_bare ::= term(t)",
        /*  19 */ "term ::= Term(x)",
        /*  20 */ "comparison ::= Including",
        /*  21 */ "comparison ::= Equal",
        /*  22 */ "comparison ::= NotEqual",
        /*  23 */ "comparison ::= LessThan",
        /*  24 */ "comparison ::= LessThanOrEqual",
        /*  25 */ "comparison ::= GreaterThan",
        /*  26 */ "comparison ::= GreaterThanOrEqual",
    ]

    // Function definitions

    func yyTokenToSymbol(_ token: CitronToken) -> CitronSymbol {
        return .yy0(token)
    }

    func yyInvokeCodeBlockForRule(ruleNumber: CitronRuleNumber) throws -> CitronSymbol {
        switch (ruleNumber) {
        case 0: /* filter ::= term(k) comparison(c) term(v) */
            func codeBlockForRule00(k: String, c: Comparison, v: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 6)

    return SearchFilter.keyValue(k, c, v)

#sourceLocation()
}
            if case .yy36(let k) = yySymbolOnStack(distanceFromTop: 2),
               case .yy26(let c) = yySymbolOnStack(distanceFromTop: 1),
               case .yy36(let v) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy3(try codeBlockForRule00(k: k, c: c, v: v))
            }
        case 1: /* filter ::= term(k) comparison(c) SingleQuote terms_double_quote(v) SingleQuote */
            func codeBlockForRule01(k: String, c: Comparison, v: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 9)

    return SearchFilter.keyValue(k, c, v)

#sourceLocation()
}
            if case .yy36(let k) = yySymbolOnStack(distanceFromTop: 4),
               case .yy26(let c) = yySymbolOnStack(distanceFromTop: 3),
               case .yy36(let v) = yySymbolOnStack(distanceFromTop: 1) {
                return .yy3(try codeBlockForRule01(k: k, c: c, v: v))
            }
        case 2: /* filter ::= term(k) comparison(c) DoubleQuote terms_single_quote(v) DoubleQuote */
            func codeBlockForRule02(k: String, c: Comparison, v: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 12)

    return SearchFilter.keyValue(k, c, v)

#sourceLocation()
}
            if case .yy36(let k) = yySymbolOnStack(distanceFromTop: 4),
               case .yy26(let c) = yySymbolOnStack(distanceFromTop: 3),
               case .yy36(let v) = yySymbolOnStack(distanceFromTop: 1) {
                return .yy3(try codeBlockForRule02(k: k, c: c, v: v))
            }
        case 3: /* filter ::= SingleQuote terms_double_quote(v) SingleQuote */
            func codeBlockForRule03(v: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 15)

    return SearchFilter.name(v)

#sourceLocation()
}
            if case .yy36(let v) = yySymbolOnStack(distanceFromTop: 1) {
                return .yy3(try codeBlockForRule03(v: v))
            }
        case 4: /* filter ::= DoubleQuote terms_single_quote(v) DoubleQuote */
            func codeBlockForRule04(v: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 18)

    return SearchFilter.name(v)

#sourceLocation()
}
            if case .yy36(let v) = yySymbolOnStack(distanceFromTop: 1) {
                return .yy3(try codeBlockForRule04(v: v))
            }
        case 5: /* filter ::= terms_bare(v) */
            func codeBlockForRule05(v: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 21)

    return SearchFilter.name(v)

#sourceLocation()
}
            if case .yy36(let v) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy3(try codeBlockForRule05(v: v))
            }
        case 6: /* terms_single_quote ::= term(t) Whitespace(w) terms_single_quote(ts) */
            func codeBlockForRule06(t: String, w: Token, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 26)

    return "\(t) \(ts)"

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let w) = yySymbolOnStack(distanceFromTop: 1),
               case .yy36(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule06(t: t, w: w, ts: ts))
            }
        case 7: /* terms_single_quote ::= term(t) Comparison(c) terms_single_quote(ts) */
            func codeBlockForRule07(t: String, c: Token, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 29)

    return "\(t)\(c)\(ts)"

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let c) = yySymbolOnStack(distanceFromTop: 1),
               case .yy36(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule07(t: t, c: c, ts: ts))
            }
        case 8: /* terms_single_quote ::= term(t) SingleQuote terms_single_quote(ts) */
            func codeBlockForRule08(t: String, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 32)

    return "\(t)'\(ts)"

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy36(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule08(t: t, ts: ts))
            }
        case 9: /* terms_single_quote ::= term(t) */
            func codeBlockForRule09(t: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 35)

    return t

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule09(t: t))
            }
        case 10: /* terms_double_quote ::= term(t) Whitespace(w) terms_double_quote(ts) */
            func codeBlockForRule10(t: String, w: Token, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 40)

    return "\(t) \(ts)"

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let w) = yySymbolOnStack(distanceFromTop: 1),
               case .yy36(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule10(t: t, w: w, ts: ts))
            }
        case 11: /* terms_double_quote ::= term(t) Comparison(c) terms_double_quote(ts) */
            func codeBlockForRule11(t: String, c: Token, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 43)

    return "\(t)\(c)\(ts)"

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let c) = yySymbolOnStack(distanceFromTop: 1),
               case .yy36(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule11(t: t, c: c, ts: ts))
            }
        case 12: /* terms_double_quote ::= term(t) DoubleQuote terms_double_quote(ts) */
            func codeBlockForRule12(t: String, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 46)

    return "\(t)\"\(ts)"

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy36(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule12(t: t, ts: ts))
            }
        case 13: /* terms_double_quote ::= term(t) */
            func codeBlockForRule13(t: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 49)

    return t

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule13(t: t))
            }
        case 14: /* terms_bare ::= term(t) Whitespace(w) terms_bare(ts) */
            func codeBlockForRule14(t: String, w: Token, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 54)

    return "\(t) \(ts)"

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let w) = yySymbolOnStack(distanceFromTop: 1),
               case .yy36(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule14(t: t, w: w, ts: ts))
            }
        case 15: /* terms_bare ::= term(t) SingleQuote terms_bare(ts) */
            func codeBlockForRule15(t: String, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 57)

    return "\(t)'\(ts)"

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy36(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule15(t: t, ts: ts))
            }
        case 16: /* terms_bare ::= term(t) DoubleQuote terms_bare(ts) */
            func codeBlockForRule16(t: String, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 60)

    return "\(t)\"\(ts)"

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy36(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule16(t: t, ts: ts))
            }
        case 17: /* terms_bare ::= term(t) Comparison(c) terms_bare(ts) */
            func codeBlockForRule17(t: String, c: Token, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 63)

    return "\(t)\(c)\(ts)"

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let c) = yySymbolOnStack(distanceFromTop: 1),
               case .yy36(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule17(t: t, c: c, ts: ts))
            }
        case 18: /* terms_bare ::= term(t) */
            func codeBlockForRule18(t: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 66)

    return t

#sourceLocation()
}
            if case .yy36(let t) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule18(t: t))
            }
        case 19: /* term ::= Term(x) */
            func codeBlockForRule19(x: Token) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 71)

    if case .term(let t) = x {
        return t
    } else {
        preconditionFailure("lexer did not return Token.term for the Term token")
    }

#sourceLocation()
}
            if case .yy0(let x) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy36(try codeBlockForRule19(x: x))
            }
        case 20: /* comparison ::= Including */
            func codeBlockForRule20() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 80)

    .including

#sourceLocation()
}
            return .yy26(try codeBlockForRule20())
        case 21: /* comparison ::= Equal */
            func codeBlockForRule21() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 83)

    .equal

#sourceLocation()
}
            return .yy26(try codeBlockForRule21())
        case 22: /* comparison ::= NotEqual */
            func codeBlockForRule22() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 86)

    .notEqual

#sourceLocation()
}
            return .yy26(try codeBlockForRule22())
        case 23: /* comparison ::= LessThan */
            func codeBlockForRule23() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 89)

    .lessThan

#sourceLocation()
}
            return .yy26(try codeBlockForRule23())
        case 24: /* comparison ::= LessThanOrEqual */
            func codeBlockForRule24() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 92)

    .lessThanOrEqual

#sourceLocation()
}
            return .yy26(try codeBlockForRule24())
        case 25: /* comparison ::= GreaterThan */
            func codeBlockForRule25() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 95)

    .greaterThan

#sourceLocation()
}
            return .yy26(try codeBlockForRule25())
        case 26: /* comparison ::= GreaterThanOrEqual */
            func codeBlockForRule26() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 98)

    .greaterThanOrEqual

#sourceLocation()
}
            return .yy26(try codeBlockForRule26())
        default:
            fatalError("Can't invoke code block for rule number \(ruleNumber) - no such rule")
        }
        fatalError("Can't resolve types correctly for invoking code block for rule number \(ruleNumber)")
    }

    private func yySymbolOnStack(distanceFromTop: Int) -> CitronSymbol {
        assert(yyStack.count > distanceFromTop)
        return yyStack[yyStack.count - 1 - distanceFromTop].symbol
    }

    func yyUnwrapResultFromSymbol(_ symbol: CitronSymbol) -> CitronResult {
        if case .yy3(let result) = symbol {
            return result
        } else {
            fatalError("Unexpected mismatch in result type")
        }
    }

    // Error capturing

    typealias CitronErrorCaptureDelegate = _MagicCardSearchGrammarCitronErrorCaptureDelegate

    weak var errorCaptureDelegate: CitronErrorCaptureDelegate? = nil

    let yyErrorCaptureSymbolNumbersForState: [CitronStateNumber:[CitronSymbolNumber]] = [:]
    let yyCanErrorCapture: Bool = false
    let yyErrorCaptureDirectives: [CitronSymbolNumber:(endAfter:[[CitronTokenCode]],endBefore:[CitronTokenCode])] = [:]
    let yyErrorCaptureEndBeforeTokens: Set<CitronSymbolNumber> = []

    let yyErrorCaptureEndAfterSequenceEndingTokens: Set<CitronSymbolNumber> = []

    func yyShouldSaveErrorForCapturing(error: Error) -> Bool {
        fatalError("This parser was not generated with error capturing information")
    }

    func yyCaptureError(on symbolCode: CitronNonTerminalCode, error: Error, state: CitronErrorCaptureState) -> CitronSymbol? {
        fatalError("This parser was not generated with error capturing information")
    }

    func yySymbolContent(_ symbol: CitronSymbol) -> Any { return symbol.typeErasedContent() }

    let yyStartSymbolNumber: CitronSymbolNumber = 13
    let yyEndStateNumber: CitronStateNumber = 20

    var yyErrorCaptureSavedError: (error: Error, isLexerError: Bool)? = nil
    var yyErrorCaptureTokensSinceError: [(token: CitronToken, tokenCode: CitronTokenCode)] = []
    var yyErrorCaptureStackIndices: [Int] = []
    var yyErrorCaptureStartSymbolStackIndex: Int? = nil

    var numberOfCapturedErrors: Int = 0
}

protocol _MagicCardSearchGrammarCitronErrorCaptureDelegate : AnyObject {
    func shouldSaveErrorForCapturing(error: Error) -> Bool
}

extension _MagicCardSearchGrammarCitronErrorCaptureDelegate {
    func shouldSaveErrorForCapturing(error: Error) -> Bool {
        return true
    }
}

// Ability to use == to compare CitronSymbolCode with CitronTokenCode / CitronNonTerminalCode

extension MagicCardSearchGrammar.CitronSymbolCode {
    static func == (a: MagicCardSearchGrammar.CitronSymbolCode, b: MagicCardSearchGrammar.CitronTokenCode) -> Bool {
        guard case let .token(code) = a else { return false }
        return (code == b)
    }
    static func == (a: MagicCardSearchGrammar.CitronTokenCode, b: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        guard case let .token(code) = b else { return false }
        return (code == a)
    }
    static func == (a: MagicCardSearchGrammar.CitronSymbolCode, b: MagicCardSearchGrammar.CitronNonTerminalCode) -> Bool {
        guard case let .nonterminal(code) = a else { return false }
        return (code == b)
    }
    static func == (a: MagicCardSearchGrammar.CitronNonTerminalCode, b: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        guard case let .nonterminal(code) = b else { return false }
        return (code == a)
    }
}

// Ability to use switch (symbolCode) { case .tokenCode: ...; case .nonterminalCode: ... }

extension MagicCardSearchGrammar.CitronSymbolCode {
    static func ~= (pattern: MagicCardSearchGrammar.CitronTokenCode, value: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
    static func ~= (pattern: MagicCardSearchGrammar.CitronNonTerminalCode, value: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
}
