// This file is automatically generated by Citron version 2.0.
//
// The parser class defined below conforms to the CitronParser protocol
// defined in CitronParser.swift. 
// 
// The authors of Citron disclaim copyright to the source code in this file.

// Parser class

class MagicCardSearchGrammar: CitronParser {

    // Types

    typealias CitronSymbolNumber = UInt8
    typealias CitronStateNumber = UInt8
    typealias CitronRuleNumber = UInt8

    enum CitronTokenCode: CitronSymbolNumber {
      case SingleQuote                    =   1
      case DoubleQuote                    =   2
      case Whitespace                     =   3
      case Comparison                     =   4
      case Term                           =   5
      case Equal                          =   6
      case NotEqual                       =   7
      case LessThan                       =   8
      case LessThanOrEqual                =   9
      case GreaterThan                    =  10
      case GreaterThanOrEqual             =  11
    }

    enum CitronNonTerminalCode: CitronSymbolNumber {
      case filter                         =  12
      case term                           =  13
      case comparison                     =  14
      case terms_double_quote             =  15
      case terms_single_quote             =  16
    }

    enum CitronSymbolCode : RawRepresentable, Equatable {
        case token(CitronTokenCode)
        case nonterminal(CitronNonTerminalCode)
        case endOfInput

        init(_ token: CitronTokenCode) { self = .token(token) }
        init(_ nonterminal: CitronNonTerminalCode) { self = .nonterminal(nonterminal) }
        init(rawValue: CitronSymbolNumber) {
            if (rawValue == 0) {
                self = .endOfInput
            } else if (rawValue < 12) {
                self = .token(CitronTokenCode(rawValue: rawValue)!)
            } else if (rawValue < 17) {
                self = .nonterminal(CitronNonTerminalCode(rawValue: rawValue)!)
            } else {
                fatalError()
            }
        }

        typealias RawValue = CitronSymbolNumber
        var rawValue: CitronSymbolNumber {
            switch (self) {
            case .token(let t): return t.rawValue
            case .nonterminal(let nt): return nt.rawValue
            case .endOfInput: return 0
            }
        }
    }

    typealias CitronToken = Token

    enum CitronSymbol {
        case yyBaseOfStack
        case yy0(CitronToken)
        case yy6(String)
        case yy7(Comparison)
        case yy9(SearchFilter)

        func typeErasedContent() -> Any {
            switch (self) {
            case .yyBaseOfStack: fatalError()
            case .yy0(let value): return value as Any
            case .yy6(let value): return value as Any
            case .yy7(let value): return value as Any
            case .yy9(let value): return value as Any
            }
        }
    }

    typealias CitronResult = SearchFilter

    // Counts

    let yyNumberOfSymbols: Int = 17
    let yyNumberOfStates: Int = 24

    // Action tables

    let yyLookaheadAction: [(CitronSymbolNumber, CitronParsingAction)] = [
/*   0 */  ( 6, .SR(14)), ( 7, .SR(15)), ( 8, .SR(16)), ( 9, .SR(17)), (10, .SR(18)),
/*   5 */  (11, .SR(19)), ( 1, .SH( 2)), ( 2, .SH( 1)), ( 1, .SH(10)), ( 2, .SH( 6)),
/*  10 */  ( 5, .SR(13)), ( 1, .SH( 3)), ( 5, .SR(13)), ( 3, .SH( 5)), ( 4, .SH( 4)),
/*  15 */  ( 2, .SH( 7)), ( 3, .SH( 9)), ( 4, .SH( 8)), (12, .ACCEPT),   (13, .SH(11)),
/*  20 */  ( 1, .SH(17)), (13, .SH(13)), (13, .SH(23)), ( 5, .SR(13)), (16, .SH(16)),
/*  25 */  (13, .SH(14)), ( 2, .SH(15)), (15, .SH(18)), (13, .SH(13)), (13, .SH(13)),
/*  30 */  (13, .SH(13)), (16, .RD( 7)), (16, .RD( 6)), (16, .RD( 5)), (14, .SH(12)),
/*  35 */  (13, .SH(13)), ( 0, .RD( 4)), ( 0, .RD( 3)), (16, .SH(20)), (13, .SH(14)),
/*  40 */  ( 0, .RD( 2)), (15, .RD(11)), (13, .SH(14)), (13, .SH(14)), (15, .RD(10)),
/*  45 */  (15, .RD( 9)), (13, .SH(14)), ( 2, .SH(19)), (15, .SH(22)), ( 0, .RD( 1)),
/*  50 */  (17, .RD( 2)), ( 1, .SH(21)), ( 0, .RD( 0)),
    ]

    let yyShiftUseDefault: Int = 53
    let yyShiftOffsetMin: Int = -6
    let yyShiftOffsetMax: Int = 52
    let yyShiftOffset: [Int] = [
        /*     0 */     5,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        /*    10 */    18,   -6,    7,   10,   13,   36,   24,   37,   19,   40,
        /*    20 */    45,   49,   50,   52,
    ]

    let yyReduceUseDefault: Int = -1
    let yyReduceOffsetMin: Int =   0
    let yyReduceOffsetMax: Int =   33
    let yyReduceOffset: [Int] = [
        /*     0 */     6,    8,   12,   15,   16,   17,   22,   26,   29,   30,
        /*    10 */    33,   20,    9,
    ]

    let yyDefaultAction: [CitronParsingAction] = [
  /*     0 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*     5 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*    10 */  .ERROR , .ERROR , .ERROR , .RD( 8), .RD(12),
  /*    15 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*    20 */  .ERROR , .ERROR , .ERROR , .ERROR ,
    ]

    // Fallback

    let yyHasFallback: Bool = false
    let yyFallback: [CitronSymbolNumber] = []

    // Wildcard

    let yyWildcard: CitronSymbolNumber? = nil

    // Rules

    let yyRuleInfo: [(lhs: CitronSymbolNumber, nrhs: UInt)] = [
        (lhs: 12, nrhs: 3),
        (lhs: 12, nrhs: 5),
        (lhs: 12, nrhs: 5),
        (lhs: 12, nrhs: 3),
        (lhs: 12, nrhs: 3),
        (lhs: 16, nrhs: 3),
        (lhs: 16, nrhs: 3),
        (lhs: 16, nrhs: 3),
        (lhs: 16, nrhs: 1),
        (lhs: 15, nrhs: 3),
        (lhs: 15, nrhs: 3),
        (lhs: 15, nrhs: 3),
        (lhs: 15, nrhs: 1),
        (lhs: 13, nrhs: 1),
        (lhs: 14, nrhs: 1),
        (lhs: 14, nrhs: 1),
        (lhs: 14, nrhs: 1),
        (lhs: 14, nrhs: 1),
        (lhs: 14, nrhs: 1),
        (lhs: 14, nrhs: 1),
    ]

    // Stack

    var yyStack: [(stateOrRule: CitronStateOrRule , symbolCode: CitronSymbolNumber, symbol: CitronSymbol)]  = [
        (stateOrRule: .state(0), symbolCode: 0, symbol: .yyBaseOfStack)
    ]
    var maxStackSize: Int? = nil
    var maxAttainedStackSize: Int = 0

    // Tracing

    var isTracingEnabled: Bool = false
    var isTracingPrintsSymbolValues: Bool = false
    var isTracingPrintsTokenValues: Bool = false
    let yySymbolName: [String] = [
    /*  0 */ "$",
    /*  1 */ "SingleQuote",
    /*  2 */ "DoubleQuote",
    /*  3 */ "Whitespace",
    /*  4 */ "Comparison",
    /*  5 */ "Term",
    /*  6 */ "Equal",
    /*  7 */ "NotEqual",
    /*  8 */ "LessThan",
    /*  9 */ "LessThanOrEqual",
    /* 10 */ "GreaterThan",
    /* 11 */ "GreaterThanOrEqual",
    /* 12 */ "filter",
    /* 13 */ "term",
    /* 14 */ "comparison",
    /* 15 */ "terms_double_quote",
    /* 16 */ "terms_single_quote",
    ]
    let yyRuleText: [String] = [
        /*   0 */ "filter ::= term(k) comparison(c) term(v)",
        /*   1 */ "filter ::= term(k) comparison(c) SingleQuote terms_double_quote(v) SingleQuote",
        /*   2 */ "filter ::= term(k) comparison(c) DoubleQuote terms_single_quote(v) DoubleQuote",
        /*   3 */ "filter ::= SingleQuote terms_double_quote(v) SingleQuote",
        /*   4 */ "filter ::= DoubleQuote terms_single_quote(v) DoubleQuote",
        /*   5 */ "terms_single_quote ::= term(t) Whitespace(w) terms_single_quote(ts)",
        /*   6 */ "terms_single_quote ::= term(t) Comparison(c) terms_single_quote(ts)",
        /*   7 */ "terms_single_quote ::= term(t) SingleQuote terms_single_quote(ts)",
        /*   8 */ "terms_single_quote ::= term(t)",
        /*   9 */ "terms_double_quote ::= term(t) Whitespace(w) terms_double_quote(ts)",
        /*  10 */ "terms_double_quote ::= term(t) Comparison(c) terms_double_quote(ts)",
        /*  11 */ "terms_double_quote ::= term(t) DoubleQuote terms_double_quote(ts)",
        /*  12 */ "terms_double_quote ::= term(t)",
        /*  13 */ "term ::= Term(x)",
        /*  14 */ "comparison ::= Equal",
        /*  15 */ "comparison ::= NotEqual",
        /*  16 */ "comparison ::= LessThan",
        /*  17 */ "comparison ::= LessThanOrEqual",
        /*  18 */ "comparison ::= GreaterThan",
        /*  19 */ "comparison ::= GreaterThanOrEqual",
    ]

    // Function definitions

    func yyTokenToSymbol(_ token: CitronToken) -> CitronSymbol {
        return .yy0(token)
    }

    func yyInvokeCodeBlockForRule(ruleNumber: CitronRuleNumber) throws -> CitronSymbol {
        switch (ruleNumber) {
        case 0: /* filter ::= term(k) comparison(c) term(v) */
            func codeBlockForRule00(k: String, c: Comparison, v: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 6)

    return SearchFilter(k, c, v)

#sourceLocation()
}
            if case .yy6(let k) = yySymbolOnStack(distanceFromTop: 2),
               case .yy7(let c) = yySymbolOnStack(distanceFromTop: 1),
               case .yy6(let v) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy9(try codeBlockForRule00(k: k, c: c, v: v))
            }
        case 1: /* filter ::= term(k) comparison(c) SingleQuote terms_double_quote(v) SingleQuote */
            func codeBlockForRule01(k: String, c: Comparison, v: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 9)

    return SearchFilter(k, c, v)

#sourceLocation()
}
            if case .yy6(let k) = yySymbolOnStack(distanceFromTop: 4),
               case .yy7(let c) = yySymbolOnStack(distanceFromTop: 3),
               case .yy6(let v) = yySymbolOnStack(distanceFromTop: 1) {
                return .yy9(try codeBlockForRule01(k: k, c: c, v: v))
            }
        case 2: /* filter ::= term(k) comparison(c) DoubleQuote terms_single_quote(v) DoubleQuote */
            func codeBlockForRule02(k: String, c: Comparison, v: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 12)

    return SearchFilter(k, c, v)

#sourceLocation()
}
            if case .yy6(let k) = yySymbolOnStack(distanceFromTop: 4),
               case .yy7(let c) = yySymbolOnStack(distanceFromTop: 3),
               case .yy6(let v) = yySymbolOnStack(distanceFromTop: 1) {
                return .yy9(try codeBlockForRule02(k: k, c: c, v: v))
            }
        case 3: /* filter ::= SingleQuote terms_double_quote(v) SingleQuote */
            func codeBlockForRule03(v: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 15)

    return SearchFilter("name", .equal, v)

#sourceLocation()
}
            if case .yy6(let v) = yySymbolOnStack(distanceFromTop: 1) {
                return .yy9(try codeBlockForRule03(v: v))
            }
        case 4: /* filter ::= DoubleQuote terms_single_quote(v) DoubleQuote */
            func codeBlockForRule04(v: String) throws -> SearchFilter {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 18)

    return SearchFilter("name", .equal, v)

#sourceLocation()
}
            if case .yy6(let v) = yySymbolOnStack(distanceFromTop: 1) {
                return .yy9(try codeBlockForRule04(v: v))
            }
        case 5: /* terms_single_quote ::= term(t) Whitespace(w) terms_single_quote(ts) */
            func codeBlockForRule05(t: String, w: Token, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 23)

    return "\(t)\(w)\(ts)"

#sourceLocation()
}
            if case .yy6(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let w) = yySymbolOnStack(distanceFromTop: 1),
               case .yy6(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy6(try codeBlockForRule05(t: t, w: w, ts: ts))
            }
        case 6: /* terms_single_quote ::= term(t) Comparison(c) terms_single_quote(ts) */
            func codeBlockForRule06(t: String, c: Token, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 26)

    return "\(t)\(c)\(ts)"

#sourceLocation()
}
            if case .yy6(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let c) = yySymbolOnStack(distanceFromTop: 1),
               case .yy6(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy6(try codeBlockForRule06(t: t, c: c, ts: ts))
            }
        case 7: /* terms_single_quote ::= term(t) SingleQuote terms_single_quote(ts) */
            func codeBlockForRule07(t: String, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 29)

    return "\(t)'\(ts)"

#sourceLocation()
}
            if case .yy6(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy6(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy6(try codeBlockForRule07(t: t, ts: ts))
            }
        case 8: /* terms_single_quote ::= term(t) */
            func codeBlockForRule08(t: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 32)

    return t

#sourceLocation()
}
            if case .yy6(let t) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy6(try codeBlockForRule08(t: t))
            }
        case 9: /* terms_double_quote ::= term(t) Whitespace(w) terms_double_quote(ts) */
            func codeBlockForRule09(t: String, w: Token, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 37)

    return "\(t)\(w)\(ts)"

#sourceLocation()
}
            if case .yy6(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let w) = yySymbolOnStack(distanceFromTop: 1),
               case .yy6(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy6(try codeBlockForRule09(t: t, w: w, ts: ts))
            }
        case 10: /* terms_double_quote ::= term(t) Comparison(c) terms_double_quote(ts) */
            func codeBlockForRule10(t: String, c: Token, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 40)

    return "\(t)\(c)\(ts)"

#sourceLocation()
}
            if case .yy6(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let c) = yySymbolOnStack(distanceFromTop: 1),
               case .yy6(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy6(try codeBlockForRule10(t: t, c: c, ts: ts))
            }
        case 11: /* terms_double_quote ::= term(t) DoubleQuote terms_double_quote(ts) */
            func codeBlockForRule11(t: String, ts: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 43)

    return "\(t)\"\(ts)"

#sourceLocation()
}
            if case .yy6(let t) = yySymbolOnStack(distanceFromTop: 2),
               case .yy6(let ts) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy6(try codeBlockForRule11(t: t, ts: ts))
            }
        case 12: /* terms_double_quote ::= term(t) */
            func codeBlockForRule12(t: String) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 46)

    return t

#sourceLocation()
}
            if case .yy6(let t) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy6(try codeBlockForRule12(t: t))
            }
        case 13: /* term ::= Term(x) */
            func codeBlockForRule13(x: Token) throws -> String {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 51)

    if case .term(let t) = x {
        return t
    } else {
        preconditionFailure("lexer did not return Token.term for the Term token")
    }

#sourceLocation()
}
            if case .yy0(let x) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy6(try codeBlockForRule13(x: x))
            }
        case 14: /* comparison ::= Equal */
            func codeBlockForRule14() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 60)

    .equal

#sourceLocation()
}
            return .yy7(try codeBlockForRule14())
        case 15: /* comparison ::= NotEqual */
            func codeBlockForRule15() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 63)

    .notEqual

#sourceLocation()
}
            return .yy7(try codeBlockForRule15())
        case 16: /* comparison ::= LessThan */
            func codeBlockForRule16() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 66)

    .lessThan

#sourceLocation()
}
            return .yy7(try codeBlockForRule16())
        case 17: /* comparison ::= LessThanOrEqual */
            func codeBlockForRule17() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 69)

    .lessThanOrEqual

#sourceLocation()
}
            return .yy7(try codeBlockForRule17())
        case 18: /* comparison ::= GreaterThan */
            func codeBlockForRule18() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 72)

    .greaterThan

#sourceLocation()
}
            return .yy7(try codeBlockForRule18())
        case 19: /* comparison ::= GreaterThanOrEqual */
            func codeBlockForRule19() throws -> Comparison {
#sourceLocation(file: "MagicCardSearch/Parser/MagicCardSearchGrammar.y", line: 75)

    .greaterThanOrEqual

#sourceLocation()
}
            return .yy7(try codeBlockForRule19())
        default:
            fatalError("Can't invoke code block for rule number \(ruleNumber) - no such rule")
        }
        fatalError("Can't resolve types correctly for invoking code block for rule number \(ruleNumber)")
    }

    private func yySymbolOnStack(distanceFromTop: Int) -> CitronSymbol {
        assert(yyStack.count > distanceFromTop)
        return yyStack[yyStack.count - 1 - distanceFromTop].symbol
    }

    func yyUnwrapResultFromSymbol(_ symbol: CitronSymbol) -> CitronResult {
        if case .yy9(let result) = symbol {
            return result
        } else {
            fatalError("Unexpected mismatch in result type")
        }
    }

    // Error capturing

    typealias CitronErrorCaptureDelegate = _MagicCardSearchGrammarCitronErrorCaptureDelegate

    weak var errorCaptureDelegate: CitronErrorCaptureDelegate? = nil

    let yyErrorCaptureSymbolNumbersForState: [CitronStateNumber:[CitronSymbolNumber]] = [:]
    let yyCanErrorCapture: Bool = false
    let yyErrorCaptureDirectives: [CitronSymbolNumber:(endAfter:[[CitronTokenCode]],endBefore:[CitronTokenCode])] = [:]
    let yyErrorCaptureEndBeforeTokens: Set<CitronSymbolNumber> = []

    let yyErrorCaptureEndAfterSequenceEndingTokens: Set<CitronSymbolNumber> = []

    func yyShouldSaveErrorForCapturing(error: Error) -> Bool {
        fatalError("This parser was not generated with error capturing information")
    }

    func yyCaptureError(on symbolCode: CitronNonTerminalCode, error: Error, state: CitronErrorCaptureState) -> CitronSymbol? {
        fatalError("This parser was not generated with error capturing information")
    }

    func yySymbolContent(_ symbol: CitronSymbol) -> Any { return symbol.typeErasedContent() }

    let yyStartSymbolNumber: CitronSymbolNumber = 12
    let yyEndStateNumber: CitronStateNumber = 15

    var yyErrorCaptureSavedError: (error: Error, isLexerError: Bool)? = nil
    var yyErrorCaptureTokensSinceError: [(token: CitronToken, tokenCode: CitronTokenCode)] = []
    var yyErrorCaptureStackIndices: [Int] = []
    var yyErrorCaptureStartSymbolStackIndex: Int? = nil

    var numberOfCapturedErrors: Int = 0
}

protocol _MagicCardSearchGrammarCitronErrorCaptureDelegate : AnyObject {
    func shouldSaveErrorForCapturing(error: Error) -> Bool
}

extension _MagicCardSearchGrammarCitronErrorCaptureDelegate {
    func shouldSaveErrorForCapturing(error: Error) -> Bool {
        return true
    }
}

// Ability to use == to compare CitronSymbolCode with CitronTokenCode / CitronNonTerminalCode

extension MagicCardSearchGrammar.CitronSymbolCode {
    static func == (a: MagicCardSearchGrammar.CitronSymbolCode, b: MagicCardSearchGrammar.CitronTokenCode) -> Bool {
        guard case let .token(code) = a else { return false }
        return (code == b)
    }
    static func == (a: MagicCardSearchGrammar.CitronTokenCode, b: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        guard case let .token(code) = b else { return false }
        return (code == a)
    }
    static func == (a: MagicCardSearchGrammar.CitronSymbolCode, b: MagicCardSearchGrammar.CitronNonTerminalCode) -> Bool {
        guard case let .nonterminal(code) = a else { return false }
        return (code == b)
    }
    static func == (a: MagicCardSearchGrammar.CitronNonTerminalCode, b: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        guard case let .nonterminal(code) = b else { return false }
        return (code == a)
    }
}

// Ability to use switch (symbolCode) { case .tokenCode: ...; case .nonterminalCode: ... }

extension MagicCardSearchGrammar.CitronSymbolCode {
    static func ~= (pattern: MagicCardSearchGrammar.CitronTokenCode, value: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
    static func ~= (pattern: MagicCardSearchGrammar.CitronNonTerminalCode, value: MagicCardSearchGrammar.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
}
