excluded:
  - .build
  - scratch/
  - DerivedData
  - .swiftpm
  - Package.swift
  - MagicCardSearch/Parser/Citron/
  - MagicCardSearch/Parser/SearchFilterParser.swift

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - todo
  - line_length
  - multiple_closures_with_trailing_closure

force_cast: warning
force_try: warning

attributes:
  attributes_with_arguments_always_on_line_above: true
  always_on_same_line:
    - "@Environment"

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL
    - q
    - i
    - j
    - x
    - "y"

trailing_comma:
  severity: error
  mandatory_comma: true

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - ID

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 2
    error: 4

cyclomatic_complexity:
  warning: 10
  error: 20

large_tuple:
  warning: 3
  error: 4

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

strict: true

reporter: "xcode"

#custom_rules:
#  # Encourage use of Swift Concurrency over Dispatch
#  avoid_dispatch_queue:
#    name: "Avoid DispatchQueue"
#    regex: "DispatchQueue\\.(main|global)"
#    message: "Consider using Swift Concurrency (async/await) instead of DispatchQueue"
#    severity: warning
#
#  # Encourage modern Swift syntax
#  avoid_completion_handler:
#    name: "Consider async/await"
#    regex: "@escaping\\s*\\([^)]*\\)\\s*->\\s*Void"
#    message: "Consider using async/await instead of completion handlers for new code"
#    severity: warningsw
