// This file is automatically generated by Citron version 2.0.
//
// The parser class defined below conforms to the CitronParser protocol
// defined in CitronParser.swift. 
// 
// The authors of Citron disclaim copyright to the source code in this file.

// Parser class

class PartialFilterQueryParser: CitronParser {

    // Types

    typealias CitronSymbolNumber = UInt8
    typealias CitronStateNumber = UInt8
    typealias CitronRuleNumber = UInt8

    enum CitronTokenCode: CitronSymbolNumber {
      case Or                             =   1
      case Verbatim                       =   2
      case And                            =   3
      case OpenParen                      =   4
      case CloseParen                     =   5
    }

    enum CitronNonTerminalCode: CitronSymbolNumber {
      case query                          =   6
      case disjunction                    =   7
      case conjunction                    =   8
      case parenthesized                  =   9
    }

    enum CitronSymbolCode : RawRepresentable, Equatable {
        case token(CitronTokenCode)
        case nonterminal(CitronNonTerminalCode)
        case endOfInput

        init(_ token: CitronTokenCode) { self = .token(token) }
        init(_ nonterminal: CitronNonTerminalCode) { self = .nonterminal(nonterminal) }
        init(rawValue: CitronSymbolNumber) {
            if (rawValue == 0) {
                self = .endOfInput
            } else if (rawValue < 6) {
                self = .token(CitronTokenCode(rawValue: rawValue)!)
            } else if (rawValue < 10) {
                self = .nonterminal(CitronNonTerminalCode(rawValue: rawValue)!)
            } else {
                fatalError()
            }
        }

        typealias RawValue = CitronSymbolNumber
        var rawValue: CitronSymbolNumber {
            switch (self) {
            case .token(let t): return t.rawValue
            case .nonterminal(let nt): return nt.rawValue
            case .endOfInput: return 0
            }
        }
    }

    typealias CitronToken = PartialFilterQueryTokenContent

    enum CitronSymbol {
        case yyBaseOfStack
        case yy0(CitronToken)
        case yy14(PartialFilterQuery)

        func typeErasedContent() -> Any {
            switch (self) {
            case .yyBaseOfStack: fatalError()
            case .yy0(let value): return value as Any
            case .yy14(let value): return value as Any
            }
        }
    }

    typealias CitronResult = PartialFilterQuery

    // Counts

    let yyNumberOfSymbols: Int = 10
    let yyNumberOfStates: Int = 8

    // Action tables

    let yyLookaheadAction: [(CitronSymbolNumber, CitronParsingAction)] = [
/*   0 */  ( 6, .ACCEPT),   ( 7, .SH( 5)), ( 8, .SH( 6)), ( 9, .RD( 4)), ( 7, .SH( 4)),
/*   5 */  ( 8, .SH( 6)), ( 9, .RD( 4)), ( 2, .SR( 3)), ( 9, .RD( 6)), ( 4, .SH( 1)),
/*  10 */  ( 8, .SH( 7)), ( 9, .RD( 4)), ( 2, .SR( 5)), ( 1, .SH( 2)), ( 4, .SH( 1)),
/*  15 */  ( 0, .RD( 0)), ( 1, .SH( 2)), ( 5, .SR( 7)), (10, .RD( 2)), ( 3, .SH( 3)),
    ]

    let yyShiftUseDefault: Int = 20
    let yyShiftOffsetMin: Int = 0
    let yyShiftOffsetMax: Int = 16
    let yyShiftOffset: [Int] = [
        /*     0 */     5,    5,    5,   10,   12,   15,   16,   16,
    ]

    let yyReduceUseDefault: Int = -7
    let yyReduceOffsetMin: Int =   -6
    let yyReduceOffsetMax: Int =   2
    let yyReduceOffset: [Int] = [
        /*     0 */    -6,   -3,    2,   -1,
    ]

    let yyDefaultAction: [CitronParsingAction] = [
  /*     0 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*     5 */  .ERROR , .RD( 1), .RD( 2),
    ]

    // Fallback

    let yyHasFallback: Bool = false
    let yyFallback: [CitronSymbolNumber] = []

    // Wildcard

    let yyWildcard: CitronSymbolNumber? = nil

    // Rules

    let yyRuleInfo: [(lhs: CitronSymbolNumber, nrhs: UInt)] = [
        (lhs: 6, nrhs: 1),
        (lhs: 7, nrhs: 1),
        (lhs: 7, nrhs: 3),
        (lhs: 8, nrhs: 1),
        (lhs: 8, nrhs: 1),
        (lhs: 8, nrhs: 3),
        (lhs: 8, nrhs: 3),
        (lhs: 9, nrhs: 3),
    ]

    // Stack

    var yyStack: [(stateOrRule: CitronStateOrRule , symbolCode: CitronSymbolNumber, symbol: CitronSymbol)]  = [
        (stateOrRule: .state(0), symbolCode: 0, symbol: .yyBaseOfStack)
    ]
    var maxStackSize: Int? = nil
    var maxAttainedStackSize: Int = 0

    // Tracing

    var isTracingEnabled: Bool = false
    var isTracingPrintsSymbolValues: Bool = false
    var isTracingPrintsTokenValues: Bool = false
    let yySymbolName: [String] = [
    /*  0 */ "$",
    /*  1 */ "Or",
    /*  2 */ "Verbatim",
    /*  3 */ "And",
    /*  4 */ "OpenParen",
    /*  5 */ "CloseParen",
    /*  6 */ "query",
    /*  7 */ "disjunction",
    /*  8 */ "conjunction",
    /*  9 */ "parenthesized",
    ]
    let yyRuleText: [String] = [
        /*   0 */ "query ::= disjunction(d)",
        /*   1 */ "disjunction ::= conjunction(c)",
        /*   2 */ "disjunction ::= disjunction(d) Or conjunction(c)",
        /*   3 */ "conjunction ::= Verbatim(v)",
        /*   4 */ "conjunction ::= parenthesized(d)",
        /*   5 */ "conjunction ::= conjunction(c) And Verbatim(v)",
        /*   6 */ "conjunction ::= conjunction(c) And parenthesized(d)",
        /*   7 */ "parenthesized ::= OpenParen(l) disjunction(d) CloseParen(r)",
    ]

    // Function definitions

    func yyTokenToSymbol(_ token: CitronToken) -> CitronSymbol {
        return .yy0(token)
    }

    func yyInvokeCodeBlockForRule(ruleNumber: CitronRuleNumber) throws -> CitronSymbol {
        switch (ruleNumber) {
        case 0: /* query ::= disjunction(d) */
            func codeBlockForRule0(d: PartialFilterQuery) throws -> PartialFilterQuery {
#sourceLocation(file: "MagicCardSearch/Parser/PartialFilterQuery/PartialFilterQueryGrammar.y", line: 6)
 d 
#sourceLocation()
}
            if case .yy14(let d) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy14(try codeBlockForRule0(d: d))
            }
        case 1: /* disjunction ::= conjunction(c) */
            func codeBlockForRule1(c: PartialFilterQuery) throws -> PartialFilterQuery {
#sourceLocation(file: "MagicCardSearch/Parser/PartialFilterQuery/PartialFilterQueryGrammar.y", line: 9)
 c 
#sourceLocation()
}
            if case .yy14(let c) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy14(try codeBlockForRule1(c: c))
            }
        case 2: /* disjunction ::= disjunction(d) Or conjunction(c) */
            func codeBlockForRule2(d: PartialFilterQuery, c: PartialFilterQuery) throws -> PartialFilterQuery {
#sourceLocation(file: "MagicCardSearch/Parser/PartialFilterQuery/PartialFilterQueryGrammar.y", line: 10)

    .or(.positive, [d, c])

#sourceLocation()
}
            if case .yy14(let d) = yySymbolOnStack(distanceFromTop: 2),
               case .yy14(let c) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy14(try codeBlockForRule2(d: d, c: c))
            }
        case 3: /* conjunction ::= Verbatim(v) */
            func codeBlockForRule3(v: PartialFilterQueryTokenContent) throws -> PartialFilterQuery {
#sourceLocation(file: "MagicCardSearch/Parser/PartialFilterQuery/PartialFilterQueryGrammar.y", line: 15)

    if v.content.first == "-" {
        .term(
            .init(
                .negative,
                String(v.content.suffix(from: v.content.index(after: v.content.startIndex))),
            ),
        )
    } else {
        .term(.init(.positive, v.content))
    }

#sourceLocation()
}
            if case .yy0(let v) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy14(try codeBlockForRule3(v: v))
            }
        case 4: /* conjunction ::= parenthesized(d) */
            func codeBlockForRule4(d: PartialFilterQuery) throws -> PartialFilterQuery {
#sourceLocation(file: "MagicCardSearch/Parser/PartialFilterQuery/PartialFilterQueryGrammar.y", line: 27)
 d 
#sourceLocation()
}
            if case .yy14(let d) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy14(try codeBlockForRule4(d: d))
            }
        case 5: /* conjunction ::= conjunction(c) And Verbatim(v) */
            func codeBlockForRule5(c: PartialFilterQuery, v: PartialFilterQueryTokenContent) throws -> PartialFilterQuery {
#sourceLocation(file: "MagicCardSearch/Parser/PartialFilterQuery/PartialFilterQueryGrammar.y", line: 28)

    let string: PolarityString = if v.content.first == "-" {
        .init(
            .negative,
            String(v.content.suffix(from: v.content.index(after: v.content.startIndex))),
        )
    } else {
        .init(.positive, v.content)
    }
    return .and(.positive, [c, .term(string)])

#sourceLocation()
}
            if case .yy14(let c) = yySymbolOnStack(distanceFromTop: 2),
               case .yy0(let v) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy14(try codeBlockForRule5(c: c, v: v))
            }
        case 6: /* conjunction ::= conjunction(c) And parenthesized(d) */
            func codeBlockForRule6(c: PartialFilterQuery, d: PartialFilterQuery) throws -> PartialFilterQuery {
#sourceLocation(file: "MagicCardSearch/Parser/PartialFilterQuery/PartialFilterQueryGrammar.y", line: 39)

    .and(.positive, [c, d])

#sourceLocation()
}
            if case .yy14(let c) = yySymbolOnStack(distanceFromTop: 2),
               case .yy14(let d) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy14(try codeBlockForRule6(c: c, d: d))
            }
        case 7: /* parenthesized ::= OpenParen(l) disjunction(d) CloseParen(r) */
            func codeBlockForRule7(l: PartialFilterQueryTokenContent, d: PartialFilterQuery, r: PartialFilterQueryTokenContent) throws -> PartialFilterQuery {
#sourceLocation(file: "MagicCardSearch/Parser/PartialFilterQuery/PartialFilterQueryGrammar.y", line: 44)

    .or(l.content.first == "-" ? .negative : .positive, [d])

#sourceLocation()
}
            if case .yy0(let l) = yySymbolOnStack(distanceFromTop: 2),
               case .yy14(let d) = yySymbolOnStack(distanceFromTop: 1),
               case .yy0(let r) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy14(try codeBlockForRule7(l: l, d: d, r: r))
            }
        default:
            fatalError("Can't invoke code block for rule number \(ruleNumber) - no such rule")
        }
        fatalError("Can't resolve types correctly for invoking code block for rule number \(ruleNumber)")
    }

    private func yySymbolOnStack(distanceFromTop: Int) -> CitronSymbol {
        assert(yyStack.count > distanceFromTop)
        return yyStack[yyStack.count - 1 - distanceFromTop].symbol
    }

    func yyUnwrapResultFromSymbol(_ symbol: CitronSymbol) -> CitronResult {
        if case .yy14(let result) = symbol {
            return result
        } else {
            fatalError("Unexpected mismatch in result type")
        }
    }

    // Error capturing

    typealias CitronErrorCaptureDelegate = _PartialFilterQueryParserCitronErrorCaptureDelegate

    weak var errorCaptureDelegate: CitronErrorCaptureDelegate? = nil

    let yyErrorCaptureSymbolNumbersForState: [CitronStateNumber:[CitronSymbolNumber]] = [:]
    let yyCanErrorCapture: Bool = false
    let yyErrorCaptureDirectives: [CitronSymbolNumber:(endAfter:[[CitronTokenCode]],endBefore:[CitronTokenCode])] = [:]
    let yyErrorCaptureEndBeforeTokens: Set<CitronSymbolNumber> = []

    let yyErrorCaptureEndAfterSequenceEndingTokens: Set<CitronSymbolNumber> = []

    func yyShouldSaveErrorForCapturing(error: Error) -> Bool {
        fatalError("This parser was not generated with error capturing information")
    }

    func yyCaptureError(on symbolCode: CitronNonTerminalCode, error: Error, state: CitronErrorCaptureState) -> CitronSymbol? {
        fatalError("This parser was not generated with error capturing information")
    }

    func yySymbolContent(_ symbol: CitronSymbol) -> Any { return symbol.typeErasedContent() }

    let yyStartSymbolNumber: CitronSymbolNumber = 6
    let yyEndStateNumber: CitronStateNumber = 5

    var yyErrorCaptureSavedError: (error: Error, isLexerError: Bool)? = nil
    var yyErrorCaptureTokensSinceError: [(token: CitronToken, tokenCode: CitronTokenCode)] = []
    var yyErrorCaptureStackIndices: [Int] = []
    var yyErrorCaptureStartSymbolStackIndex: Int? = nil

    var numberOfCapturedErrors: Int = 0
}

protocol _PartialFilterQueryParserCitronErrorCaptureDelegate : AnyObject {
    func shouldSaveErrorForCapturing(error: Error) -> Bool
}

extension _PartialFilterQueryParserCitronErrorCaptureDelegate {
    func shouldSaveErrorForCapturing(error: Error) -> Bool {
        return true
    }
}

// Ability to use == to compare CitronSymbolCode with CitronTokenCode / CitronNonTerminalCode

extension PartialFilterQueryParser.CitronSymbolCode {
    static func == (a: PartialFilterQueryParser.CitronSymbolCode, b: PartialFilterQueryParser.CitronTokenCode) -> Bool {
        guard case let .token(code) = a else { return false }
        return (code == b)
    }
    static func == (a: PartialFilterQueryParser.CitronTokenCode, b: PartialFilterQueryParser.CitronSymbolCode) -> Bool {
        guard case let .token(code) = b else { return false }
        return (code == a)
    }
    static func == (a: PartialFilterQueryParser.CitronSymbolCode, b: PartialFilterQueryParser.CitronNonTerminalCode) -> Bool {
        guard case let .nonterminal(code) = a else { return false }
        return (code == b)
    }
    static func == (a: PartialFilterQueryParser.CitronNonTerminalCode, b: PartialFilterQueryParser.CitronSymbolCode) -> Bool {
        guard case let .nonterminal(code) = b else { return false }
        return (code == a)
    }
}

// Ability to use switch (symbolCode) { case .tokenCode: ...; case .nonterminalCode: ... }

extension PartialFilterQueryParser.CitronSymbolCode {
    static func ~= (pattern: PartialFilterQueryParser.CitronTokenCode, value: PartialFilterQueryParser.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
    static func ~= (pattern: PartialFilterQueryParser.CitronNonTerminalCode, value: PartialFilterQueryParser.CitronSymbolCode) -> Bool {
        return (pattern == value)
    }
}
